comm call on stats peer review
ropensci/roweb3 pull request #146
Opened 2021-02-12 18:28 UTC by stefaniebutland

2021-02-14 18:51 UTC, alexpghayes requested changes

2021-02-14 18:51 UTC, alexpghayes commented on content/author/alex-hayes/_index.md
> +---
```suggestion
orcid: 0000-0002-4985-5160
---
```

2021-02-14 18:51 UTC, alexpghayes commented on content/commcalls/2021-03-02/index.md
> +    bio: Alex Hayes is a PhD student in the University of Wisconsin-Madison statistics program. Alex on [GitHub](https://github.com/alexpghayes), [Twitter](https://twitter.com/alexpghayes), [Website]
```suggestion
    bio: Alex Hayes is a PhD student in the University of Wisconsin-Madison statistics program, studying community detection in networks. He also maintains the [`broom`](https://broom.tidymodels.org/) package. Alex on [GitHub](https://github.com/alexpghayes), [Twitter](https://twitter.com/alexpghayes), [Website](https://www.alexpghayes.com/)
```

2021-02-16 18:09 UTC, stefaniebutland commented
draft tweet
[Community Call] rOpenSci Statistical Software Testing and Peer Review

With @noamross @bikesRdata @annakrystalli @alexpghayes @JohnSakaluk

Tues March 2, 9-10am PST / 17:00 UTC

- Intro to project
- new tools to prep software for submission
- live walk-through

https://ropensci.org/commcalls/feb2021-statsreview/

#RStats

2021-02-17 15:41 UTC, merged