Commcall blogpost: foster pkg community
ropensci/roweb3 pull request #194
Opened 2021-04-26 19:16 UTC by sinarueeger

2021-04-27 08:25 UTC, mpadge requested changes

2021-04-27 08:25 UTC, mpadge commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +Scientific software development - and with that R packages - is a community effort. While there are often just a handful of developers maintaining an R package, the development really starts to thriv
"code base" is maybe overly-nerdy? Maybe sentence could simply finish at "users start to contribute"?

2021-04-27 08:25 UTC, mpadge commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +In principle, every open source package has an unspoken open invitation to contribute. The question is how this invisible rule can be turned into something more explicit (and less intimidating) so th
Remove "unspoken open invitation" -> "open invitation", because invitations to contribute are often explicit

2021-04-27 08:25 UTC, mpadge commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +During one hour, several  speakers mentioned the bits and pieces of an R package that invite code contribution and manage expectations of users/contributors (say a contributor guide or using well-def
This sentence seems a bit higgeldy-piggeldy, with brackets and semi-colons breaking up the flow. If i may, an attempt at re-writing:

> Over the course of an hour, the four speakers emphasised various aspects of an R package that can be used to invite code contributions, and to manage expectations of both users and contributors, for example through a contributor guide, or through explicit instructions how to use issues on GitHub. Speakers also emphasised the importance of the "soft skills" of package maintainers, especially the importance of considering the effect of how package maintainers interact with contributors, such as fostering opportunities to learn, being kind when saying "no", and always acknolwedging contributions.

Feel free to take any bits of what i've done to create a hybrid between yours and mine. Hope that helps :smiley_cat:

2021-04-27 08:25 UTC, mpadge commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +A package has many different actors - the package authors, the users, the contributors - and they may act more or less with each other.
Suggestion: Change "more or less with each other", because that ultimately doesn't say much, to something like, "they may act and interact with each other in a variety of ways."

2021-04-27 08:25 UTC, mpadge commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +Before diving into tips, Maëlle talked about how authors can improve their communication with contributors. Being kind will certainly retain contributors, rather than driving them away. But emojis ca
> Being kind will certainly retain contributors, rather than driving them away.

Instead of finishing on a negative, that could maybe better be rewritten, "One of the best ways to encourage and retain contributors is simply being kind"? Then  followed with "*And* emojis can also ..." rather than "But emojis can also." Finally, "compensate for *lack* of nuance."

2021-04-27 10:42 UTC, sinarueeger commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +During one hour, several  speakers mentioned the bits and pieces of an R package that invite code contribution and manage expectations of users/contributors (say a contributor guide or using well-def
Were it not three speakers?

2021-04-27 10:43 UTC, sinarueeger commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +During one hour, several  speakers mentioned the bits and pieces of an R package that invite code contribution and manage expectations of users/contributors (say a contributor guide or using well-def
I left the "in principle" sentence, hope thats ok.

2021-04-27 10:44 UTC, sinarueeger commented
@mpadge thanks for the fixes! all very helpful and implemented them all.

2021-04-27 10:55 UTC, mpadge commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +During one hour, several  speakers mentioned the bits and pieces of an R package that invite code contribution and manage expectations of users/contributors (say a contributor guide or using well-def
> Were it not three speakers?

oh yeah, sorry bout the confusion there!

2021-04-27 15:41 UTC, sinarueeger commented
@mpadge is there anything I still need to change from my side? (it says "changes requested")

2021-04-27 15:58 UTC, steffilazerte reviewed
Hi @sinarueeger! 

This is FANTASTIC! You've put so much work into this! The screenshots really add to it and the summaries are very useful.

As per your questions:
1. Pictures look great :grin:
2. I fixed a very few minor typos
3. I added some label-athon details and fixed some links 
4. I added some video links (to the heading for each speaker, etc.) [**Is this what you had in mind? Should I add more?**]
5. Tags are good!

I have a couple of comments for you to think about. Namely, you have to be an author on this post!

I'll add a couple more questions to the end, and will ping the others for a quick sign off when I'm done. Other than that I think we're good to go once you add your author file and check my one other comment.

* [X] post follows Content Guidelines
* [X] post follows Style Guide
* [X] title is in Title Case
* [X] publication date is ok
* [X] alternative text of images is informative
* [X] Twitter metadata looks ok (paste post preview link in [Twitter card validator](https://cards-dev.twitter.com/validator); might have to click twice on "Preview card")
* [ ] author metadata is provided with correct folder name
* [X] html not included in pull request of Rmd post
* [X] I ran `roblog::ro_lint_md()` on index.md
* [X] I ran `roblog::ro_check_urls()` on index.md
* [X] I ran a spell-check on index.md
* [X] YAML subject tags are ok ("tech notes" for tech notes; "community" for non-staff non-editor)

2021-04-27 15:58 UTC, steffilazerte commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +  - Maëlle Salmon
You MUST be an author! This a great summary post and you should receive kudos and credit for it. You'll just need to create an [author file](https://blogguide.ropensci.org/technical.html#createauthorfile), then you'll be good to go! **Note** that your author file should have the same umlauts as your name does here. 
```suggestion
  - Sina Rüeger
  - Maëlle Salmon
```

2021-04-27 15:58 UTC, steffilazerte commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +In GitHub, disable "allow edits from maintainers", as this is demotivating ("Don't take the keyboard from the learner", Carpentry)
I think the idea might be more to not use that option, rather than to disable it. I think only the person who created the pull request can disable it, but I'm not 100% sure. 

```suggestion
In GitHub, don't abuse "allow edits from maintainers", as this is demotivating ("Don't take the keyboard from the learner", Carpentry)
```

2021-04-27 16:11 UTC, mpadge commented
Thanks so much @sinarueeger - couldn't agree more with @steffilazerte about the overall fantasticness of this. Very nicely -- and very, very quickly - done indeed!

2021-04-27 16:11 UTC, sinarueeger commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +In GitHub, disable "allow edits from maintainers", as this is demotivating ("Don't take the keyboard from the learner", Carpentry)
Well put - you are right.

2021-04-27 16:12 UTC, sinarueeger commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +  - Maëlle Salmon
I'll quickly create an author file.

2021-04-27 16:13 UTC, sinarueeger commented
@steffilazerte 
> I added some video links (to the heading for each speaker, etc.) [Is this what you had in mind? Should I add more?]
This is perfect! Thanks for adding the links.

2021-04-27 16:19 UTC, sinarueeger commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +  - Maëlle Salmon
Ok, I did that, fingers crossed that my beloved umlaute don't mess things up :-)

2021-04-27 16:38 UTC, steffilazerte commented
Okay! I think we're good to go!

@maelle, @Bisaloo, @mpadge as you are all authors on this blog, could you take a quick perusal and let me know if you're okay with us publishing tomorrow? I'll ping you all on Slack too, just in case :wink:

Thanks everyone!

2021-04-27 17:15 UTC, stefaniebutland commented
This is fantastic!! Thank you @sinarueeger @mpadge @steffilazerte

2021-04-27 17:46 UTC, maelle reviewed
This is so awesome Sina! (I'm not surprised at all of course!) Thank you for doing this!

2021-04-27 17:46 UTC, maelle commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +#### 2. Add them in publicly visible places
Standard places?

2021-04-27 18:26 UTC, steffilazerte commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +#### 2. Add them in publicly visible places
What do you mean by standard places exactly?

2021-04-28 07:28 UTC, Bisaloo approved these changes
Thank you for this great work :clap:!

I love the introduction in particular! :star_struck:

> In principle, every open source package has an open invitation to contribute. The question is how this invisible rule can be turned into something more explicit (and less intimidating) so that users who want to contribute can do so easily and feel welcomed and at ease.

:100: :100: :100:

2021-04-28 07:28 UTC, Bisaloo commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +- Disable unimportant bots (Hugo mentioned the the notoriously confusing coverage bot)
```suggestion
- Disable unimportant bots (Hugo mentioned the notoriously confusing coverage bot)
```

2021-04-28 09:49 UTC, sinarueeger commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +#### 2. Add them in publicly visible places
@maelle do you mean - "add them in standard places"?

2021-04-28 15:21 UTC, merged

2021-04-29 06:54 UTC, maelle commented on content/blog/2021-04-27-commcall-pkg-community/index.md
> +#### 2. Add them in publicly visible places
it was to add to "publicly visible" but it's not important at all. Thanks again!