draft censo2017
ropensci/roweb3 pull request #226
Opened 2021-06-24 22:51 UTC by pachadotdev

2021-07-06 22:48 UTC, steffilazerte commented
Thanks @pachadotdev! Sorry I've been slow (busy at the useR conference!) but I'll review within the next few days. 

@noamross I'll be reviewing for editorial stuff soon, but as this package was the first to be reviewed in Spanish, and the Spanish review process was an outcome of your discussions during a community call, would you be able to give it a review too? We'll be asking @maurolepore to come in later and review the Spanish translation (to come!) 

Thanks!

2021-07-07 15:04 UTC, noamross requested changes
Great post, I just had a few small comments.  While I like the narrative arc, I do think it's usually better to have the first paragraph or two give an introduction that summarizes what is to come (e.g., this post is about this package, the problem it solved, how to use it, and the fact that the package and its review process were all in Spanish).

2021-07-07 15:04 UTC, noamross commented on content/blog/2021-06-20-censo2017.md
> +It was a pleasure for me to count on thoughtful reviews from the same people who I reviewed their contributions to [R for Data Science in Spanish](https://es.r4ds.hadley.nz/) long ago in 2019. If the
I don't think this paragraph is that necessary.  If you remove it, you can move the links to the next paragraph in a sentence that mentions them as other initiatives in Spanish-language R resources.

2021-07-08 02:37 UTC, steffilazerte reviewed
Hi Pachá! 

This is looking great, I love the thoughtfulness, and the narrative (as Noam put it). I have just a couple of comments/suggestions (13) left to go. 

I'm away next week Monday through Thursday and I don't want to hold up the process. Noam's and my suggestions are fairly minor, so once you address them, go right ahead and work on the Spanish translation when you have time (i.e. don't wait for me, unless you really want my feedback; I'll leave it up to you to ping me if that's the case).

When you've added the Spanish translation, ping @maurolepore for the Spanish review, and @stefaniebutland for a publication date! We're almost there! Thanks again for your hard work on this post. 

* [X] post follows Content Guidelines
* [x] post follows Style Guide
    - Remove \`  ` from all package names (i.e., censo2017 and citesdb)
* [x] title is in Title Case
  - Definitely in title case, but see what you think about suggestions for being a bit more detailed
* [ ] publication date is ok
  - We'll ask @stefaniebutland after @maurolepore has a chance to look at it
* [X] alternative text of images is informative
* [X] Twitter metadata looks ok (paste post preview link in [Twitter card validator](https://cards-dev.twitter.com/validator); might have to click twice on "Preview card")
* [X] author metadata is provided with correct folder name
* [X] html not included in pull request of Rmd post
* [X] I ran `roblog::ro_lint_md()` on index.md
* [X] I ran `roblog::ro_check_urls()` on index.md
* [X] I ran a spell-check on index.md
* [X] YAML subject tags are ok ("tech notes" for tech notes; "community" for non-staff non-editor)
* [X] YAML package-version included
* [X] YAML subject tags - software peer review, packagename
* [X] acknowledges and links to reviewers
* [x] links to peer review thread
  - I've suggested a couple of places

2021-07-08 02:37 UTC, steffilazerte commented on content/blog/2021-06-20-censo2017.md
> +title: 'censo2017 - The Story Behind the Package'
Can we get something about this being the first package to be reviewed in Spanish here?
Perhaps:

- "The Story Behind censo2017, the First rOpenSci Package to be Reviewed in Spanish" or
- "censo2017 - The Story Behind the First rOpenSci Package to be Reviewed in Spanish"

What do you think?

2021-07-08 21:28 UTC, pachadotdev commented
hi
i added all of the comments

2021-07-08 22:17 UTC, steffilazerte reviewed
So speedy :grin: I fixed one typo and added the link to your packages review issue. @noamross what do you think?

2021-07-08 22:17 UTC, steffilazerte commented on content/blog/2021-06-20-censo2017.md
> +My goal wasn’t to extract statistical secrets, which is not posible with these datasets, I just wanted to obtain values of population by age intervals for different regions, among other similar aggre
```suggestion
My goal wasn’t to extract statistical secrets, which is not possible with these datasets, I just wanted to obtain values of population by age intervals for different regions, among other similar aggregations, which is something that dplyr and other tools ease a lot. After being able to convert the datasets and the description of variables to CSV/XML, I found that the effort in doing that justified creating an R package to organize my work.
```

2021-07-08 22:17 UTC, steffilazerte commented on content/blog/2021-06-20-censo2017.md
> +The help of rOpenSci and its software review was pivotal. Dedicated reviewers, [María Paula Caldas](https://www.mpaulacaldas.com/), [Frans van Dunné](https://www.fransvandunne.com/) and [Melina Vidon
Link to review issue for your package

```suggestion
The help of rOpenSci and its [software review](https://github.com/ropensci/software-review/issues/414) was pivotal. Dedicated reviewers, [María Paula Caldas](https://www.mpaulacaldas.com/), [Frans van Dunné](https://www.fransvandunne.com/) and [Melina Vidoni](/author/melina-vidoni/), tested the package and suggested enhancements. Their reviews were very helpful, they gave extremely valuable advice and were really supportive of my work and the development of the package. I had the chance to interact with them in the past, during R4DS translation process, where I co-wrote an article with rOpenSci's editor [Mauro Lepore](/author/mauro-lepore/), [Datos: datasets translations to promote diversity, equity, and inclusion](https://github.com/openjournals/jose-reviews/issues/99), as a result of that collaboration.
```

2021-07-09 13:09 UTC, noamross commented
Looks good to me!

2021-07-09 14:01 UTC, steffilazerte commented
Great! @pachadotdev go ahead with the Spanish. I'm away most of next week, so when that's done, ping @maurolepore for review, and @stefaniebutland for a publication date.

2021-07-10 02:41 UTC, pachadotdev commented
btw, the docs work now https://docs.ropensci.org/censo2017/
thanks to Jeroen who fixed the internals and now I can install sf on the CI

2021-07-10 16:16 UTC, pachadotdev commented
@maurolepore querido, he subido el post en espaniol aparte de la version en inglés

2021-07-12 17:38 UTC, maurolepore approved these changes
Muchas gracias por este articulo! Se lo ve muy bien. Lo apruebo pero por favor considera mis sugerencias.

Que honor que el primer paquete revisado en espaniol sea tuyo! Gracias por tu contribucion.

2021-07-12 17:38 UTC, maurolepore commented on content/blog/2021-06-20-censo2017-espaniol.md
> +Para obtener información detallada de cada municipio/región en relación con las preguntas anteriores, tenemos que pensar en los datos de REDATAM como un árbol, y es necesario unir "zonas" con "vivien
No entiendo el significado de "lo que es nada" pero la oracion tiene sentido sin eso. Creo "rapidamente" es mas preciso que "nada de tiempo". Sugiero:

> Esto se hace rapidamente con el backend DuckDB.

2021-07-12 17:38 UTC, maurolepore commented on content/blog/2021-06-20-censo2017-espaniol.md
> +
Creo que es mejor elimiar "simple" y "tiene mucho sentido" para no herir a quienes encuentren la cuenta y tabla resultante dificiles de entender.

2021-07-12 17:38 UTC, maurolepore commented on content/blog/2021-06-20-censo2017-espaniol.md
> +Para conocer la proporción de hombres (1) y mujeres (2) por región, es muy similar.
Creo que esta oracion se lee mejor escribiendo explicitamente "el codigo" (o el sujeto que corresponda). Sugiero:

> "..., [el codigo] es muy similar."

2021-07-12 17:38 UTC, maurolepore commented on content/blog/2021-06-20-censo2017-espaniol.md
> +# Enlaces con formación y política
Esta seccion parece contaner dos partes -- una conclusion de la utilidad del paquete, y una opinion politica. Necesitas dos encabezados en vez de solo uno?

2021-07-12 17:38 UTC, maurolepore commented on content/blog/2021-06-20-censo2017-espaniol.md
> +Las universidades y centros de investigación en América Latina carecen de financiamiento y los gobiernos no tienen una agenda política basada en la evidencia, lo cual es una combinación peligrosa. Ch
Es este un buen espacio para ofrecer una opinion politica? 

En tal caso, creo que este parrafo necesita informacion mas precisa, por ejemplo, la palabra "carecer" sugiere "cero" pero -- sin saber -- supongo que mas preciso seria "poco" o "menos que XXX anios atras".

2021-07-12 17:38 UTC, maurolepore commented on content/blog/2021-06-20-censo2017-espaniol.md
> +La ayuda de rOpenSci y su [revisión de software](https://github.com/ropensci/software-review/issues/414) fue fundamental. Los revisores, [María Paula Caldas](https://www.mpaulacaldas.com/), [Frans va
Sugiero eliminar la comma en "... Frans van Dunne y Melina Vidoni[,] probaron el paquete"

2021-07-12 17:38 UTC, maurolepore commented on content/blog/2021-06-20-censo2017-espaniol.md
> +La ayuda de rOpenSci y su [revisión de software](https://github.com/ropensci/software-review/issues/414) fue fundamental. Los revisores, [María Paula Caldas](https://www.mpaulacaldas.com/), [Frans va
Sugiero eliminar la siguiente oracion. El haber trabajado antes con los revisores sugiere un conflicto de interes. Y el haber trajabado juntos es un honor para mi pero parece poco relacionado a censo2017. 

> Tuve la oportunidad de interactuar con ellos en el pasado, durante el proceso de traducción de R4DS, donde co-escribí un artículo con el editor de rOpenSci [Mauro Lepore](/autor/mauro-lepore/), [Datos: traducciones de conjuntos de datos para promover la diversidad, la equidad y la inclusión](https://github.com/openjournals/jose-reviews/issues/99), como resultado de esa colaboración.

2021-07-12 17:38 UTC, maurolepore commented on content/blog/2021-06-20-censo2017-espaniol.md
> +Me encantaría ver diferentes "copias" de censo2017 en los países vecinos Perú y Bolivia, y el resto de la región. Crear el primer paquete de rOpenSci totalmente documentado en español no sólo tiene q
Esta oracion parece compleja. Quizas puedas descomponerla en partes mas pequenias?

> Crear el primer paquete de rOpenSci totalmente documentado en español no sólo tiene que ver con la inclusión, que obviamente es deseable, sino que también tiene que ver con la productividad, porque en América Latina, los materiales que están documentados en inglés son difíciles de entender y por lo tanto las herramientas no son adoptadas como uno quisiera.

2021-07-12 17:38 UTC, maurolepore commented on content/blog/2021-06-20-censo2017-espaniol.md
> +Creo que hago lo mejor que puedo para contribuir a iniciativas como rOpenSci porque aquí he encontrado mi lugar y he descubierto a otros que tienen el deseo de pasar de la ignorancia al conocimiento
Sugiero reemplazer "pasar de la ignorancia al conocimiento en" por "aprender".

> ... he descubierto a otros que tienen el deseo de [aprender] muchas cosas diferentes ...

2021-07-14 15:48 UTC, pachadotdev commented
@maurolepore anoche arreglé todo lo que comentabas, cualquier punto de diferencia lo dejé fuera, para mantener el común denominador

2021-07-19 00:28 UTC, pachadotdev commented
hi
it's all ready, and I added an example with maps

hola
está todo listo y he agregado un ejemplo con mapas

2021-07-19 18:18 UTC, pachadotdev reviewed
> Muchas gracias por este articulo! Se lo ve muy bien. Lo apruebo pero por favor considera mis sugerencias.
> 
> Que honor que el primer paquete revisado en espaniol sea tuyo! Gracias por tu contribucion.

muchas gracias, Mauro!
incluí todos tus comentarios y pasé tijeras... me fui por lo típico chileno y todo lo que no era "de consenso", quedó fuera (es la única forma de que el resultado sea de consenso, creo)
agregué un mapa del hacinamiento, pues creo que meustra un tema socioeconómico importante
había otras opciones como la cantidad de phds por barrio y otros temas que no van más allá de crear algo anecdótico, pero el hacinamiento es un tema muy serio en la gestión local

2021-07-20 20:17 UTC, steffilazerte reviewed
Hooray! We have a publication date of Tuesday, July 27th 2021!

You'll notice that I made two changes to the pull request:
- I moved the md files into their respective folders and renamed them to index.md
- I changed the 'slug' for the Spanish version to 'censo2017-es'.

This way, there'll be two posts, one in English and one in Spanish. This also means that your overcrowding figure is displayed properly (it wasn't visible otherwise). 


Last things to do:

- [ ] look at the final suggestions I've made and see if you want to accept them
- [ ] I've suggested a link at the beginning of each, leading to the other post. Can you translate the text for the Spanish version for me? Thanks!
- [ ] Change all headings from # to ## (sorry! I missed that in the first round, it needs to be ## or the spacing won't be right.)
- [ ] Change the dates in the yaml and in the folders to 2021-07-27

I'll draft a tweet in the next few days, and ask you for feedback, then if you wouldn't mind, could you create a Spanish version so we can make sure we have tweets in English and Spanish?

So close! Thanks for your work on this!

2021-07-20 20:17 UTC, steffilazerte commented on content/blog/2021-06-20-censo2017/index.md
> +{{< imgtxt src="mean-overcrowding-map.png" alt="mean overcrowding map" >}}
consider using 'figure', for a nicer, bigger picture, and a more detailed alternative text
```suggestion
{{< figure src="mean-overcrowding-map.png" alt="Map of the Metropolitan Region showing polygons representing neighbourhoods and coloured by the degree of overcrowding" >}}
```

2021-07-20 20:17 UTC, steffilazerte commented on content/blog/2021-06-20-censo2017-espaniol/index.md
> +{{< imgtxt src="mapa-hacinamiento-medio.png" alt="mapa de hacinamiento medio" >}}
Consider using "figure" for a nicer, bigger image. Also, see my suggestion in the English version for a more informative alternative text. 

```suggestion
{{< figure src="mapa-hacinamiento-medio.png" alt="mapa de hacinamiento medio" >}}
```

2021-07-20 20:17 UTC, steffilazerte commented on content/blog/2021-06-20-censo2017-espaniol/index.md
> +date: '2021-06-20'
Also change the name of the folder!
```suggestion
date: '2021-07-27'
```

2021-07-20 20:17 UTC, steffilazerte commented on content/blog/2021-06-20-censo2017-espaniol/index.md
> +  - censo2017
```suggestion
  - censo2017
  - Spanish
```

2021-07-20 20:17 UTC, steffilazerte commented on content/blog/2021-06-20-censo2017-espaniol/index.md
> +
Could you translate into Spanish: "See the English version of this blog post" Thanks!

```suggestion
> See the English version of this blog post: 
> [The Story Behind censo2017, the First rOpenSci Package to be Reviewed in Spanish](/blog/2021/07/27/censo2017)
```

2021-07-20 20:17 UTC, steffilazerte commented on content/blog/2021-06-20-censo2017/index.md
> +
```suggestion
> See the Spanish version of this blog post: 
> [La Historia de censo2017, el Primer Paquete de rOpenSci Revisado en Español](/blog/2021/07/27/censo2017-es)
```

2021-07-22 05:02 UTC, pachadotdev commented
> * look at the final suggestions I've made and see if you want to accept them
> 
> *

- [x] look at the final suggestions I've made and see if you want to accept them _accepted with no repairs_
- [x] I've suggested a link at the beginning of each, leading to the other post. Can you translate the text for the Spanish version for me? Thanks! _translated, thanks!_
- [x] Change all headings from # to ## (sorry! I missed that in the first round, it needs to be ## or the spacing won't be right.) _ready_
- [x] Change the dates in the yaml and in the folders to 2021-07-27 _ready_

2021-07-22 21:06 UTC, steffilazerte commented
Looks great! Thanks :grin: We're ready to publish on Tuesday, the only last thing I'll ask of you is to review this draft text for a tweet (below), and then translate it into Spanish for me (we'll send it out from the rOpenSci account). Thank you! 🙏🏼 

---
[blog] The Story Behind censo2017, the First rOpenSci Package to be Reviewed in Spanish by @pachadotdev

Accessing Chilean 🇨🇱 census data has never been easier!

https://ropensci.org/blog/2021/06/27/censo2017/

#rstats

(1/2)

---

And perhaps best of all, this package was both written AND reviewed in Spanish to maximize accessibility!

🙏 Thank you to rOpenSci reviewers @&#8203;mapaulacaldas, @&#8203;fransvandunne & @&#8203;melvidoni for their contributions to the first ever rOpenSci Spanish package review!

(2/2)

2021-07-22 23:23 UTC, pachadotdev commented
> Looks great! Thanks grin We're ready to publish on Tuesday, the only last thing I'll ask of you is to review this draft text for a tweet (below), and then translate it into Spanish for me (we'll send it out from the rOpenSci account). Thank you! 🙏🏼
> 
> [blog] The Story Behind censo2017, the First rOpenSci Package to be Reviewed in Spanish by @pachadotdev
> 
> Accessing Chilean chile census data has never been easier!
> 
> https://ropensci.org/blog/2021/06/27/censo2017/
> 
> #rstats
> 
> (1/2)
> 
> And perhaps best of all, this package was both written AND reviewed in Spanish to maximize accessibility!
> 
> pray Thank you to rOpenSci reviewers @​mapaulacaldas, @​fransvandunne & @​melvidoni for their contributions to the first ever rOpenSci Spanish package review!
> 
> (2/2)

@steffilazerte Hi, here are the spanish translations. Hola, aquí están las traducciones en castellano.

# tweet 1

[blog] La Historia de censo2017, el Primer Paquete de rOpenSci Revisado en Castellano por @pachadotdev 

¡Acceder a los datos del censo de Chile :chile: nunca fue más fácil!

https://ropensci.org/blog/2021/06/27/censo2017/

#rstats

(1/2)

# tweet 2

¡Quizás lo mejor de todo es que este paquete se escribió Y revisó en Español para maximizar la accesibilidad!

¡agradecemos a los revisores de rOpenSci @​mapaulacaldas, @​fransvandunne y @​melvidoni por sus aportes al primer paquete de rOpenSci jamás escrito!

(2/2)

2021-07-23 14:49 UTC, steffilazerte commented
Great! We're all done then, I'll push on Tuesday to publish and send out the tweets, and you can bask in the admiration :grin:

2021-07-27 13:57 UTC, merged