July 2021 news
ropensci/roweb3 pull request #235
Opened 2021-07-16 07:04 UTC by maelle

Waiting for a blurb by @mpadge :wink:

2021-07-16 14:44 UTC, noamross requested changes
Very exciting! I've fleshed this out a bit.

2021-07-16 14:44 UTC, noamross commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +rOpenSci's peer-review system has now [officially expanded](https://ropensci.org/blog/2019/07/15/expanding-software-review/), and we are thrilled to be able to **review statistical software in seven
```suggestion
rOpenSci's peer-review system has now [expanded](https://ropensci.org/blog/2019/07/15/expanding-software-review/) to include review of packages implementing statistical routines and algorithms.  We are thrilled to start this new chapter, for which we've developed a series of new standards and tools, and recruited a new [board of experts](https://stats-devguide.ropensci.org) to oversee.
```

2021-07-16 14:44 UTC, noamross commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +Authors of statistical software should begin by reading the [*Stats Software Dev Guide*](https://stats-devguide.ropensci.org), which describes the seven categories, along with the procedures for prep
```suggestion
Authors of statistical software should begin by reading the [*Stats Software Dev Guide*](https://stats-devguide.ropensci.org), which describes the categories of statistical software we now accept (Regression, Machine Learning, Exploratory Data Analysis, and more!), along with the procedures for preparing statistical software for peer review. It also introduces our automation tools, such as,  [the `pkgcheck` package](https://github.com/ropensci-review-tools/pkgcheck), which confirms that statistical software is ready to be submitted for review.
```

2021-07-16 14:44 UTC, noamross commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +One of our new tools developed for this system,  [the `pkgcheck` package](https://github.com/ropensci-review-tools/pkgcheck), confirms that statistical software is ready to be submitted for review.
```suggestion
```

2021-07-16 14:44 UTC, noamross commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +Submissions of statistical software begin with a pre-submission enquiry on our main [software review repository](https://github.com/ropensci/software-review).
```suggestion
Authors submitting of statistical software to review should start by opening _pre-submission inquiry_ on our main [software review repository](https://github.com/ropensci/software-review).  Inquiries are welcome well before packages are ready for submittal.  We hope authors make use of our standards and tools throughout the development process so as to make review straightforward.
```

2021-07-19 05:46 UTC, maelle commented
Thank you @noamross! I've added your edits.

2021-07-19 07:18 UTC, mpadge commented
Yes, indeed - thank you very much @noamross; now sounds much more exciting that my initial version!

2021-07-19 11:06 UTC, mpadge requested changes

2021-07-19 11:06 UTC, mpadge commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +In an R package DESCRIPTION you can use the [roles](https://www.loc.gov/marc/relators/relacode.html) found in `utils:::MARC_relator_db_codes_used_with_R`: aut, com, cph, cre, ctb, ctr, dtc, fnd, rev,
At the end of that list of roles, maybe

>  The current list of roles accepted for R packages are always listed in the output of `?person`

2021-07-20 18:36 UTC, stefaniebutland reviewed
I like the call to action of digging in the archive!

I made minor grammar changes to para 1.

2021-07-21 05:18 UTC, maelle commented
Thanks @stefaniebutland! :pray:

2021-07-21 08:37 UTC, mpadge commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +Thanks for citing our tools!
@maelle Might be worth updating your code to remove "Thanks for citing our tools" when there are no citations (like this month)?

2021-07-21 08:38 UTC, maelle commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +Thanks for citing our tools!
ah, does it sound passive agressive?

2021-07-21 08:51 UTC, mpadge commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +Thanks for citing our tools!
Not passive aggressive exactly, just odd issuing a thanks for nothing.

2021-07-22 14:21 UTC, steffilazerte reviewed
A couple of super minor wording suggestions, looks good!

2021-07-22 14:21 UTC, steffilazerte commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +Since March 2020, video recordings have closed captions.
```suggestion
As of March 2020, video recordings have closed captions.
```

2021-07-22 14:21 UTC, steffilazerte commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +We also advise to pair names with [ORCID IDs](/blog/2018/10/08/orcid/).
```suggestion
We also advise pairing names with [ORCID IDs](/blog/2018/10/08/orcid/).
```

2021-07-22 14:21 UTC, steffilazerte commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +Find out about [events](/events).
Probably not for this newsletter, but would it make sense to actually have an events section where upcoming events are listed?

2021-07-22 15:59 UTC, maelle commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +Find out about [events](/events).
That's a good idea, we've only done that for users but I like that!

2021-07-22 16:01 UTC, maelle commented on content/blog/2021-07-23-ropensci-news-digest-july-2021/index.md
> +Find out about [events](/events).
https://github.com/ropensci/biweekly/issues/75

2021-07-22 16:02 UTC, maelle commented
Thank you @steffilazerte!

2021-07-23 05:10 UTC, merged