Created rspatialdata blogpost
ropensci/roweb3 pull request #247
Opened 2021-09-15 05:06 UTC by dilinieseimon

* [x] I have read the Content Guidelines.
* [x] I have read the Technical Guidelines.
* [x] I used or followed the R Markdown or Markdown template.
* [x] I have followed the Style Guide.
* [x] I created or updated my author metadata with correct folder name.
* [x] I have added relevant tags after browsing existing tags (incuding "community" tag).
* [x] I have added the "tech notes" tag if this is a technote.
* [x] I ran `roblog::ro_lint_md()` on index.md (optional).
* [x] I ran `roblog::ro_check_urls()` on index.md (optional).
* [x] I ran a spell-check on index.md.

2021-09-15 05:57 UTC, dilinieseimon commented
@steffilazerte we are ready for review 🙋🏽‍♀️

2021-09-16 16:40 UTC, steffilazerte reviewed
@dilinieseimon, and Varsha!

Thank you so much for submitting this awesome blog post! I really enjoyed your balance between informative, yet fun and funny. It was enjoyable to read and I learned things too, always a plus 😆 

I have left comments/commit suggestions in this review, mostly relating to minor wording suggestions (totally up to you how you want to deal with those!) and a couple of more technical notes. 

I also have two more structural suggestions: 1) we'd love to see a screenshot of the rspatialdata home page near the top of the post. It's very eye-catching and is a great way of showing all that your resource has to offer (@stefaniebutland's great suggestion). 2) I'd suggest fleshing out the final paragraph into a concluding paragraph, also mentioning and linking to the tutorials that weren't rOpenSci packages. Again, this way you can direct readers to your awesome resource, and people can really get something out of it (rOpenSci package or not 😄). 

We love to give our community package authors shout-outs for their hard work, so you'll see I've added suggestions to add links to the authors for each package.

I suggest committing my suggestions (if they work for you) and 'resolve the conversation' after you've had a chance to consider my suggestion and/or implement it. That way you can keep track of the 23 suggestions I made 😁 

@mpadge Do you have time for a quick review as well?
@stefaniebutland when is a good publication date? Tuesday Sept 28th?

* [X] post follows Content Guidelines
* [X] post follows Style Guide
* [X] title is in Title Case
* [ ] publication date is ok
* [ ] alternative text of images is informative
* [ ] Twitter metadata looks ok (paste post preview link in [Twitter card validator](https://cards-dev.twitter.com/validator); might have to click twice on "Preview card")
* [X] author metadata is provided with correct folder name
* [X] html not included in pull request of Rmd post
* [X] I ran `roblog::ro_lint_md()` on index.md
* [X] I ran `roblog::ro_check_urls()` on index.md
* [X] I ran a spell-check on index.md
* [ ] YAML subject tags are ok ("tech notes" for tech notes; "community" for non-staff non-editor)

2021-09-16 16:40 UTC, steffilazerte commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +description: Using rOpenSci packages to create cool maps
Definitely want to show case rspatialdata!

```suggestion
description: "rspatialdata: tutorials for working with spatial data using R, featuring many rOpenSci packages!"
```

2021-09-16 16:40 UTC, steffilazerte commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +output:
If you decide to include the screen shot of the rspatialdata homepage, it'd be great to include as a twitter card image! You just need to update `name-of-image.png` in this suggestion (and when we get the proper publication date, the date)

```suggestion
twitterImg: blog/2021/09/14/rspatialdata/name-of-image.png
twitterAlt: "Screenshot of rspatialdata homepage featuring multicoloured tiles each outlining a different type of spatial data"
output:
```

2021-09-16 16:40 UTC, steffilazerte commented on content/author/varsha-ujjinni-vijay-kumar/_index.md
> +---
The author pages will have a photo for [Dilinie](https://deploy-preview-247--ropensci.netlify.app/author/dilinie-seimon/) but not for [Varsha](https://deploy-preview-247--ropensci.netlify.app/author/varsha-ujjinni-vijay-kumar/) because the photos are pulled from GitHub. Varsha, if this bothers you, you can create a GitHub account, update the bio info/picture and add it to your author `_index.md` and then you'll have a photo! Totally up to you, though, many [rOpenSci authors don't have photos](https://ropensci.org/author/) unless they publish regularly.

2021-09-16 16:40 UTC, steffilazerte commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +  - spatial
```suggestion
  - rnaturalearth
  - osmdata
  - MODIStsp
  - nasapower
  - rdhs
  - open-data
  - spatial
```

2021-09-16 16:40 UTC, steffilazerte commented on content/blog/2021-09-14-rspatialdata/index.md
> +> Our goal for rspatialdata was not to be a comprehensive list of R packages or tutorials, but to be a starting point for anyone to find and download spatial data related to different domains, and vi
I think it'd be nice if you could turn this final paragraph into a bit of a conclusion, perhaps listing/linking to the other tutorials/spatial data packages you have (even if they're not rOpenSci! We want to make sure you get to promote all the hard work you've done!)

2021-09-16 16:40 UTC, steffilazerte commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +## Downloading boundaries of countries using [rnaturalearth](https://cran.r-project.org/web/packages/rnaturalearth/README.html)
Here and for all the other rOpenSci packages, please link to the rOpenSci docs:
```suggestion
## Downloading boundaries of countries using [rnaturalearth](https://docs.ropensci.org/rnaturalearth)
```

2021-09-16 16:40 UTC, steffilazerte commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +The rnaturalearth package facilitates communication with [Natural earth](http://www.naturalearthdata.com/) map data. It allows us to easily download and visualise boundaries of countries and boundari
```suggestion
The rnaturalearth package (by [Andy South](https://github.com/andysouth)) facilitates communication with [Natural earth](http://www.naturalearthdata.com/) map data. It allows us to easily download and visualise boundaries of countries and boundaries of states within countries as well.
```

2021-09-16 16:40 UTC, steffilazerte commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +MODIStsp - an acronym for ‘MODIS Time Series Processing’, is an R package for downloading and pre-processing time series raster data from MODIS [data products](https://modis.gsfc.nasa.gov/data/datapr
```suggestion
MODIStsp - an acronym for ‘MODIS Time Series Processing’ (by (Lorenzo Busetto)[https://github.com/lbusett] and [Luigi Ranghetti](https://github.com/ranghetti)), is an R package for downloading and pre-processing time series raster data from MODIS [data products](https://modis.gsfc.nasa.gov/data/dataprod/).
```

2021-09-16 22:31 UTC, dilinieseimon commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +As two postgrad students on summer vacation but no travel plans (during this global pandemic of course), we took up an internship at King Abdullah University of Science and Technology (KAUST) last su
Thanks @steffilazerte! Just a bit of humour to get through these crazy times!

2021-09-16 22:49 UTC, Varsha-Ujjinni-VijayKumar commented on content/author/varsha-ujjinni-vijay-kumar/_index.md
> +---
Hey Steffi, Thank you for asking me but I think it is alright since it has got my other details.

2021-09-17 03:29 UTC, dilinieseimon commented
@steffilazerte we made the suggested changes. Let us know what you think!

2021-09-17 09:40 UTC, mpadge requested changes
This is a fantastic piece - thank you and congratulations @dilinieseimon!! My only general suggestion would be that the piece could be improved if it conveyed some kind of vision for the future of `rspatialdata`. In particular, the blog will be a really great opportunity to engage others not just in using the resource that `rspatialdata` represents, but in expanding it as well. You could conclude with an explicit call-for-participation-type thing, and in particular encouraging people to do more than just help expand the list (while still encouraging that alone). Some form of explicit encouragement for people to contribute more package descriptions, tutorials, whatever.

Great work! This is such a good and important resource already!

2021-09-17 09:40 UTC, mpadge commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +Although there is so much data being collected in multiple disciplines and made openly available, not many know how to retrieve and utilize these resources. Spatial and spatio-temporal data are two o
Can "not many know how to ..." please be changed to something that does not imply inability on the part of people, like, "it may be difficult to know ...", or "it can be difficult to find out how to ..." or something like that?

2021-09-17 09:40 UTC, mpadge commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +Although there is so much data being collected in multiple disciplines and made openly available, not many know how to retrieve and utilize these resources. Spatial and spatio-temporal data are two o
I'm also a little unsure about the claim that
> Spatial and spatio-temporal data are two of the most commonly collected data types 

but i'm equally unsure about how that might be improved? No need to change that unless you can see a better way.

2021-09-17 09:40 UTC, mpadge commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +With the R programming language becoming increasingly popular among academics, researchers, and scientists, and because spatial data is easier to interpret when visualized, Paula thought it would be
Suggestion, with request for clarification from @Paula-Moraga:

> ~~Paula~~ We though it would be a great idea ...

Otherwise the reader starts off thinking this was entirely Paula's idea, when I'd suspect a lot of ideas came from @dilinieseimon and Varsha as well.

2021-09-17 09:40 UTC, mpadge commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +This idea then became [rspatialdata](https://rspatialdata.github.io/) - a collection of data sources and tutorials on downloading and visualising spatial data using R.
> This idea ~~then~~ became

2021-09-17 09:40 UTC, mpadge commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +rspatialdata consists of a non-exhaustive list of R-packages which have been developed as clients for different spatio-temporal databases and APIs. It also consists of tutorials on how to use these R
Please hyperlink first `rspatialdata`

2021-09-17 09:40 UTC, mpadge commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +The rnaturalearth package (by [Andy South](https://github.com/andysouth)) facilitates communication with [Natural earth](http://www.naturalearthdata.com/) map data. It allows us to easily download an
I'm not sure here, but think maybe changing
> It allows us to easily download ...

to
> It allows you to easily download ...

makes it seem more inclusive and engaging? What do you think @steffilazerte?

2021-09-17 09:40 UTC, mpadge commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +osmdata (by [Mark Padgham](/author/mark-padgham/)) is an R package for downloading spatial data from [OpenStreetMap (OSM)](https://www.openstreetmap.org/) - a very cool open source project. We were a
The package actually has 4 authors, all of whom should be mentioned here: @robinlovelace, @maelle, and @hrbrmstr as well. Maybe check the other authorial attributions as well, to ensure all authors are appropriately listed?

2021-09-17 09:40 UTC, mpadge commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +osmdata (by [Mark Padgham](/author/mark-padgham/)) is an R package for downloading spatial data from [OpenStreetMap (OSM)](https://www.openstreetmap.org/) - a very cool open source project. We were a
Plus a personal political request, but could the final list maybe be changed so "motorways" does not come first? A big motivation for my software is to help move away from car-centric views of the world. "walking and bicycle paths" instead of "motorways" maybe?

2021-09-17 09:40 UTC, mpadge commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +[MODIS (Moderate Resolution Imaging Spectroradiometer)](https://modis.gsfc.nasa.gov/) is an instrument aboard the NASA Terra and Aqua satellites, which orbits the entire Earth every 1-2 days, acquiri
> Terra and Aqua satellites, which orbit~~s~~ the entire Earth

2021-09-17 09:40 UTC, mpadge commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +nasapower (by [Adam Sparks](/author/adam-sparks/)) is a client for the '[NASA POWER](https://power.larc.nasa.gov/)' global meteorology, surface solar energy and climatology data API, and aims to make
Also please hyperlink this first `nasapower` reference here

2021-09-17 09:40 UTC, mpadge commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +We downloaded relative humidity and rainfall data using the nasapower package and then visualized the relative humidity in Western Australia and the rainfall in Gansu, China.
> We downloaded relative humidity and rainfall data ~~using the nasapower package~~ and then visualized

- otherwise a bit repetitive, and it is plenty clear enough at that stage that the nasapower package was used.

2021-09-17 10:01 UTC, Robinlovelace commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +osmdata (by [Mark Padgham](/author/mark-padgham/)) is an R package for downloading spatial data from [OpenStreetMap (OSM)](https://www.openstreetmap.org/) - a very cool open source project. We were a
Thanks guys, this looks set to be a great blog post, thanks for the link-up @mpadge, and the article @dilinieseimon !

2021-09-17 11:12 UTC, Paula-Moraga commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +With the R programming language becoming increasingly popular among academics, researchers, and scientists, and because spatial data is easier to interpret when visualized, Paula thought it would be
Maybe this: Paula thought that a great project for a KAUST internship would be to create a repository

2021-09-17 14:01 UTC, steffilazerte commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +osmdata (by [Mark Padgham](/author/mark-padgham/)) is an R package for downloading spatial data from [OpenStreetMap (OSM)](https://www.openstreetmap.org/) - a very cool open source project. We were a
That was my bad! I added the authors in and didn't catch that!

2021-09-17 14:02 UTC, steffilazerte commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +nasapower (by [Adam Sparks](/author/adam-sparks/)) is a client for the '[NASA POWER](https://power.larc.nasa.gov/)' global meteorology, surface solar energy and climatology data API, and aims to make
It's hyperlinked in the title, do you think it should also be hyperlinked in the text too?

2021-09-17 14:05 UTC, steffilazerte commented
Hi @dilinieseimon, Hi @Varsha-Ujjinni-VijayKumar!

You've got a couple more suggestions now, why don't you take your time in responding, and I'll do a more complete, final review next week? We've still got plenty of time before your publication date (Tuesday, Sept 28th).

2021-09-23 21:32 UTC, steffilazerte commented
Hi @dilinieseimon Hi @Varsha-Ujjinni-VijayKumar, are you guys ready for review?

2021-09-24 00:41 UTC, dilinieseimon commented
@steffilazerte yes we are!

2021-09-24 00:43 UTC, Varsha-Ujjinni-VijayKumar commented
> Hi @dilinieseimon Hi @Varsha-Ujjinni-VijayKumar, are you guys ready for review?

@steffilazerte Yess we are!!

2021-09-24 16:54 UTC, steffilazerte reviewed
Looking great! I've added 3 small text comments and I made a tweak to the twitter card image so it shows up better (I made it bit more narrow, so now it's the `rspatialdata-home-sm.jpg` file, let me know if that's okay).

@mpadge How do you feel?

I've also prepared a draft tweet thread for when the blog is published on Tuesday, let me know if you have any comments/suggestions:

---

[blog] The Story Behind rspatialdata 🌏

🏖️ What to do on summer vacation during a global pandemic? 

📦 @dilinieeee & @uv_varsha created a collection of tutorials for R pkgs accessing spatial data!

🛣️ Check out the journey and tutorials:

https://ropensci.org/blog/2021/09/14/rspatialdata/

#RStats 

1/2


---

Featuring some awesome rOpenSci packages!

- #rnaturalearth by @&#8203;southmapr

- #osmdata by @&#8203;bikesRdata, @&#8203;robinlovelace, @&#8203;ma_salmon, and @&#8203;hrbrmstr

- #MODIStsp by Lorenzo Busetto and Luigi Ranghetti

- #nasapower by @&#8203;adamhsparks

- #rdhs by @&#8203;ojwatson92 and @&#8203;eatonjw

2/2

2021-09-24 16:54 UTC, steffilazerte commented on content/blog/2021-09-14-rspatialdata/index.md
> +Also, don't forget to have a look at our [administrative boundaries tutorial](https://rspatialdata.github.io/admin_boundaries.html) which runs you through creating outline maps of countries and their
Consider adding a heading to this section, such as "Final thoughts", or "Interested in more?" etc.
```suggestion
## Interested in more?
Have a look at our [administrative boundaries tutorial](https://rspatialdata.github.io/admin_boundaries.html) which runs you through creating outline maps of countries and their administrative divisions, our [population tutorial](https://rspatialdata.github.io/population.html) which runs you through visualizing population estimates of countries using choropleth maps and cartograms, and our tutorials on  [elevation](https://rspatialdata.github.io/elevation.html), [temperature](https://rspatialdata.github.io/temperature.html), [malaria](https://rspatialdata.github.io/malaria.html), and [air pollution](https://rspatialdata.github.io/air_pollution.html) for ideas on how to download and visualize each respective property.
```

2021-09-24 16:54 UTC, steffilazerte commented on content/blog/2021-09-14-rspatialdata/index.md
> +So if you can think of anymore R-packages that would fit into this collection or ideas on new tutorials or cool spatial visualizations, do reach out to us! Let's talk about how we can collaborate!
```suggestion
So if you think of anymore R packages that would fit into this collection, ideas on new tutorials or cool spatial visualizations, do reach out to us! Let's talk about how we can collaborate!
```

2021-09-24 16:54 UTC, steffilazerte commented on content/blog/2021-09-14-rspatialdata/index.Rmd
> +Although there is so much data being collected in multiple disciplines and made openly available, it may be difficult to find, retrieve and utilize these resources. Spatial and spatio-temporal data a
```suggestion
Although there is so much data being collected in multiple disciplines and made openly available, it can be difficult to find, retrieve and utilize these resources. Spatial and spatio-temporal data are two data types which are collected and used in research across a diverse array of domains.
```

2021-09-28 14:59 UTC, merged