Blog Post - How to cite R and R packages
ropensci/roweb3 pull request #293
Opened 2021-11-05 15:54 UTC by steffilazerte

* [X] I have read the Content Guidelines.
* [X] I have read the Technical Guidelines.
* [X] I used or followed the R Markdown or Markdown template.
* [X] I have followed the Style Guide.
* [X] I created or updated my author metadata with correct folder name.
* [X] I have added relevant tags after browsing existing tags (incuding "community" tag).
* [X] I have added the "tech notes" tag if this is a technote.
* [X] I ran `roblog::ro_lint_md()` on index.md (optional).
* [X] I ran `roblog::ro_check_urls()` on index.md (optional).
* [X] I ran a spell-check on index.md.

2021-11-05 16:46 UTC, steffilazerte commented
@maelle did you want to add anything (and then add yourself as co-author), or review? I think @stefaniebutland said she'd do a quick review too (?).

I feel like parts are a bit abrupt, but I think I could use some external input. 

If it's looking good, I could probably post for Tuesday (Nov 9th), Stef, so we keep it to one post per week?

2021-11-05 16:53 UTC, stefaniebutland commented
@steffilazerte please DM me on Slack to do a quick review when ya'll are both happy with it

2021-11-08 09:11 UTC, maelle requested changes
Thanks a lot @steffilazerte for writing this important & engaging post! I made some comments, the main one being that I wouldn't put reproducibility first as citing packages isn't directly optimal for this.

2021-11-08 09:11 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +In an ideal world, everything we use would be cited, but with word limits and editors less aware of the importance of citing software, it's often hard to justify citing everything in a manuscript.
```suggestion
In an ideal world, everything we use would be cited, but with word and references limits and editors less aware of the importance of citing software, it's often hard to justify citing everything in a manuscript. 
```

2021-11-08 09:11 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +My advice is to cite every package you think you can get away with, especially if it was a major part of your process.
```suggestion
My advice is to cite every package you think you cannot get away with, especially if it was a major part of your process.
```

?

2021-11-08 09:11 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Anything else, try to make sure it's prominently displayed in your scripts and if possible include your scripts as supplemental to the manuscript. This way any curious readers will be exposed to the
Maybe re-underline that having the packages mentioned in supplementary materials isn't enough?

2021-11-08 09:11 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Being ready to cite the packages you've used will be so much easier if you keep
Maybe mention that using a workflow tool like targets can help keep track of packages used as everything will be neatly organized?

2021-11-08 09:11 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +devtools::session_info()
but note this includes dependencies of dependencies, that one will generally _not_ cite?

2021-11-08 09:11 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +
Mention renv?

2021-11-08 09:11 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +- If you want to go next level and start managing your citations in R, checkout
Also note the tweet https://twitter.com/__jsta/status/1258419526636625920 that mentioned stuff missing from the post

2021-11-08 09:11 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +
Also

* https://github.com/Pakillo/grateful
* https://indrajeetpatil.github.io/awesome-r-pkgtools/#gratitude-

2021-11-08 09:11 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Citing R and R packages is not only important for reproducible science, but is
I don't think citing packages will be crucial for reproducibility but the point could be made that you want to track packages both for citing them and for reproducibility?

2021-11-08 09:11 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +
Maybe add a question e.g. inviting readers to share their tips or challenges? Not sure it really triggers more engagement though.

2021-11-08 09:12 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Check out the post [Make Your R Package Easier to Cite](blog/2021/02/16/package-citation/)
```suggestion
Check out the post [Make Your R Package Easier to Cite](/blog/2021/02/16/package-citation/) 
```

2021-11-08 09:29 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +1) **Reproducible Science**
Reg Docker a reference might be https://journal.r-project.org/archive/2020/RJ-2020-007/index.html

2021-11-08 19:11 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +1) **Reproducible Science**
True, I think I've been thinking about the audience of this post being scientists who might just be able to share their scripts and compile them into html reports, but for whom renv would be a bit much. 

It's definitely a good point, I think I will shuffle things around and will point out that if you want to get serious, you can explore renv or docker :grin:

2021-11-08 19:14 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +My advice is to cite every package you think you can get away with, especially if it was a major part of your process.
Not quite the meaning I wanted. I was referring to getting away with the editor not complaining :grin:

2021-11-08 19:15 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Anything else, try to make sure it's prominently displayed in your scripts and if possible include your scripts as supplemental to the manuscript. This way any curious readers will be exposed to the
Good point, this is making the best of a bad situation, not something to aim for!

2021-11-08 19:18 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +
SO COOL!!!!

2021-11-08 19:19 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Citing R and R packages is not only important for reproducible science, but is
Perhaps not strictly for *reproducibility*, but for *repeatability*?

2021-11-08 19:26 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +1) **Reproducible Science**
Also, I realize that I've confused repeatable with reproducible. Fixing that!

2021-11-08 19:39 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +2) **Developer Credit**
So funny yet sad! A great footnote to add

2021-11-08 19:51 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +
Added renv to the end along with references to docker

2021-11-08 19:52 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +- If you want to go next level and start managing your citations in R, checkout
Good idea

2021-11-08 19:54 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Citing R and R packages is not only important for reproducible science, but is
I've clarified this throughout

2021-11-08 19:54 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +
I think I'll leave it as is. Might make a good tweet comment though?

2021-11-08 20:29 UTC, steffilazerte commented
Thanks for the review @maelle! Really great point about reproducibility, made me realize that I mixed up reproducible and repeatable 🤦🏼 . Thanks for all the extra info in links etc. it really fleshes the post out!

@stefaniebutland I think it's ready for your quick review, after that @maelle can do her final check Tuesday morning (if you can!) and then I'll publish *my* Tuesday morning :grin: Sorry to make everything so last minute!

-----
Tweet draft:

[blog] How to Cite R and R Packages 📦

🙏🏻 Developers need our love, gratitude, and most important, our citations! 

🤔 Why does this matter? How do you start?

@steffilazerte's primer includes how to find citation info, wordings, and workflows. 

https://ropensci.org/blog/2021/11/16/how-to-cite-r-and-r-packages/

#RStats

2021-11-08 22:23 UTC, stefaniebutland reviewed
It's not last-minute Steffi - you were planning to do this for the 23rd :-)

I really like the motivation in the intro.

1.
>  A Roundup of R Tools for Handling BibTeX[^4]

fix citation formatting 


2. I feel like it's important to list the more "academic" reason for citation (repeatable science) before listing gratitude cause it's not primarily about being nice.

3. I think it's very important to look at, maybe paraphrase, and definitely cite existing work on software citation. See [FORCE11 Software Citation Implementation Working Group](https://www.force11.org/group/software-citation-implementation-working-group) and links therein, including [Software citation principles](https://peerj.com/articles/cs-86/) (2016) and [Software Citation Checklist for Authors](https://zenodo.org/record/3479199#.YYmfT73MKAk)(2019) which has some specifics under "What software should I cite?". Doing that puts this post in bigger context and  professionalizes your recommendation to cite software. I just noticed that the author of CFF format, Stephan Druskat, is an author on that document.

2021-11-08 23:07 UTC, steffilazerte commented
Thanks @stefaniebutland, better? Or should I give it more of an in-depth consideration?

2021-11-08 23:16 UTC, stefaniebutland approved these changes
The addition LGTM and perhaps @maelle will have deeper thoughts on it :-)

I added one word to name of working group

2021-11-08 23:16 UTC, stefaniebutland commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +The lack of citations of software in scientific publications has become a problem to the extent that working groups, such as [FORCE11 Software Citation Working Group](https://www.force11.org/group/so
```suggestion
The lack of citations of software in scientific publications has become a problem to the extent that working groups, such as [FORCE11 Software Citation Implementation Working Group](https://www.force11.org/group/software-citation-implementation-working-group), have been created to establish guidelines[^2] and standards[^3] for citing software.
```

2021-11-08 23:26 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +The lack of citations of software in scientific publications has become a problem to the extent that working groups, such as [FORCE11 Software Citation Working Group](https://www.force11.org/group/so
Done!

2021-11-08 23:27 UTC, steffilazerte commented
Great thanks! @maelle, on to you, let me know what you think when you're back at your desk (if you have time!)

2021-11-09 07:08 UTC, maelle reviewed
A few last comments, great post! :sparkles:

2021-11-09 07:08 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Including versions is also really important as a way of recording the context of your manuscript
I'd still put this last and underline that citations is not a good way to record such information.

2021-11-09 07:08 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Anything else, try to make sure it's prominently displayed in your scripts and if possible include your scripts as supplemental to the manuscript. This way any curious readers will be exposed to the
```suggestion
Anything else, try to make sure it's prominently displayed in your scripts and if possible include your scripts as supplemental to the manuscript. This way any curious readers will be exposed to the packages if nothing else. For packages like osfr, you could share your OSF page/DOI, and perhaps mention that it was managed with osfr.
```

2021-11-09 07:08 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Being ready to cite the packages you've used will be so much easier if you keep
Re-upping this comment :grin:

2021-11-09 07:08 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +or [Docker images](https://journal.r-project.org/archive/2020/RJ-2020-007/index.html),
```suggestion
or [Docker containers](https://journal.r-project.org/archive/2020/RJ-2020-007/index.html),
```

That said I am not entirely sure it's the right change

2021-11-09 15:18 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Including versions is also really important as a way of recording the context of your manuscript
I don't think I agree, now that we're talking about *repeatable* not *reproducible* science. Repeatable means you have enough information in the manuscript to repeat the general work, not that you can exactly reproduce the analysis. 

The FORCE11 Software Citation Implementation Working Group [gets at this a bit](https://peerj.com/articles/cs-86/#p-55) when they discuss provenance (reproducibility) vs. citation (repeatability).

2021-11-09 15:19 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +or [Docker images](https://journal.r-project.org/archive/2020/RJ-2020-007/index.html),
I think you're right (https://phoenixnap.com/kb/docker-image-vs-container)

2021-11-09 15:20 UTC, maelle commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Including versions is also really important as a way of recording the context of your manuscript
Ok, I can see your point!

2021-11-09 15:38 UTC, steffilazerte commented on content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd
> +Including versions is also really important as a way of recording the context of your manuscript
I've added a note here, clarifying repeatable vs. reproducible :grin:

2021-11-09 15:59 UTC, merged