Editorial Challenges in Software Peer Review (and Solutions)
ropensci/roweb3 pull request #330
Opened 2022-04-01 13:59 UTC by maelle

2022-04-01 18:18 UTC, noamross requested changes

2022-04-01 18:18 UTC, noamross commented on content/blog/2022-04-14-software-review-editorial-challenges/index.md
> +One last element that's been helpful is the sentence "If I don't hear from you within a week, I will assume you are unable to review at this time." in our [review request template](https://devguide.r
```suggestion
One challenge in reaching out to reviewers is knowing when to move on after waiting for a response.  So we've added "If I don't hear from you within a week, I will assume you are unable to review at this time." to our [standard review request template](https://devguide.ropensci.org/reviewrequesttemplate.html). This puts everyone is on the same page and provides clarity to editors and potential reviewers.
```

2022-04-01 18:18 UTC, noamross commented on content/blog/2022-04-14-software-review-editorial-challenges/index.md
> +## Reviewers' dropping out
I think this could expand a bit more with examples or color, and possibly combine it with the next section.

2022-04-01 18:18 UTC, noamross commented on content/blog/2022-04-14-software-review-editorial-challenges/index.md
> +To reduce editorial work in particular, we've improved automation, which was the topic of a community call, ["Enhancing Software Peer Review with GitHub Automation"](/commcalls/dec2021-automation/):
While this was partially covered elsewhere, I think we could expand on it here, so the post stands alone.

2022-04-01 18:18 UTC, noamross commented on content/blog/2022-04-14-software-review-editorial-challenges/index.md
> +Furthermore, we've been consistently replacing past editors and expanding the editorial team: we expect editors to handle [about 4 submissions a year](https://devdevguide.netlify.app/editorguide.html
```suggestion
A huge part of limiting work editor load is having enough editors!  We have been expanding our editorial team [LINK TO NEW EDITOR POSTS], with the goal of only expecting editors to handle [about 4 submissions a year](https://devdevguide.netlify.app/editorguide.html#editors-responsabilities).  As our submissing volume grows, and editors rotate out (we ask for 2-year commitments with option to renew), we recruit new editors largely out of our pool of reviewers. We invite experienced reviewers to guest-edit and asking if they want to stay on if their reviewers work well.  If you want to try editing [start by volunteering as a reviewer](LINK)!
```

2022-04-01 18:18 UTC, noamross commented
Nice post! I made a lot of language changes, trying to make this more of a narrative and filling in details that not all readers can be assumed to know.

2022-04-04 11:52 UTC, maelle commented
Thanks a lot @noamross!

2022-04-07 15:43 UTC, maurolepore reviewed
Lovely piece -- thanks!!

I find it clear and useful. 

My only suggestion is on this sentence, which seems worth polishing because it's close to the end.

> We've found automation, but also the existence of a communication channel between editors for solution finding as well as commiserating or encouraging, very important.

I would bring the word "important" closer to "found", then list all the important things we've found. For example: 

We've found it's very important to automate processes, communicate between editors to find solutions, and to commiserate with and encourage each other.

2022-04-12 21:09 UTC, steffilazerte reviewed
Hi @maelle,
Very nice post (as always :wink:). Your transparency and sharing these trials and tribulations is going to be really useful for others. My spouse is an editor for a scientific journal, and I know he would be able to commiserate with some of the problems and would be interested in the solutions to others. He would definitely love to be able to use chatops 😆 . 

I've made many suggestions, most of which are typo fixes, but a couple are suggestions to improve flow between sections. I found some places a bit choppy (likely the result of two distinct voices in the post!). As always, my comments are only suggestions, so take what you like and leave what you don't!

* [X] post follows Content Guidelines
* [X] post follows Style Guide
* [X] title is in Title Case
* [X] publication date is ok
* [X] alternative text of images is informative
* [X] Twitter metadata looks ok (paste post preview link in [Twitter card validator](https://cards-dev.twitter.com/validator); might have to click twice on "Preview card")
* [X] author metadata is provided with correct folder name
* [X] html not included in pull request of Rmd post
* [X] I ran `roblog::ro_lint_md()` on [index.md](http://index.md/)
* [X] I ran `roblog::ro_check_urls()` on [index.md](http://index.md/)
* [X] I ran a spell-check on [index.md](http://index.md/)
* [X] YAML subject tags are ok ("tech notes" for tech notes; "community" for non-staff non-editor)

2022-04-19 09:19 UTC, maelle commented on content/blog/2022-04-18-software-review-editorial-challenges/index.md
> +
I know right? Well done @mpadge & @xuanxu

2022-04-19 09:23 UTC, maelle commented
Thanks a ton for the super useful feedback @steffilazerte and the kind words!

2022-04-19 09:23 UTC, merged