start devguide-0.8.0 blog entry
ropensci/roweb3 pull request #343
Opened 2022-05-27 12:26 UTC by mpadge

2022-05-30 06:11 UTC, maelle reviewed
Thank you! :rocket:

2022-05-30 06:11 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +  - Maëlle Salmon
you need to list yourself first, then the rest alphabetically @mpadge

2022-05-30 06:11 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +title: "rOpenSci Dev Guide 0.7.0: Updates"
```suggestion
title: "rOpenSci Dev Guide 0.8.0: Updates"
```

2022-05-30 06:11 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +Our automation processes continue to ease the burden on all those involved in our software peer review system. This version of the Dev Guide can happily jettison an entire "approval comment template"
For the GitHub Action why not link the blog post instead?

2022-05-30 06:11 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +
You could write it's because that's a release you've been in charge of!

2022-05-30 06:11 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +Our [*Package Security Best Practices*](https://devguide.ropensci.org/package-development-security-best-practices.html) now *recommend* the use of two-factor authentication (2FA) for GitHub, and clar
```suggestion
Our [*Package Security Best Practices*](https://devguide.ropensci.org/package-development-security-best-practices.html) now *recommend* the use of two-factor authentication (2FA) for GitHub, and clarify that 2FA is [mandatory for all rOpenSci organization members and outside collaborators](/blog/2022/05/16/requiring-2fa-for-the-ropensci-github-organization/).
```

2022-05-30 06:11 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +The [section in the *Collaboration Guide* Chapter](https://devguide.ropensci.org/collaboration.html#gitflow) on "Working with collaborators" has been streamlined, with [additional links](https://gith
```suggestion
The [section in the *Collaboration Guide* Chapter](https://devguide.ropensci.org/collaboration.html#gitflow) on "Working with collaborators" has been streamlined, with [additional links](https://github.com/ropensci/dev_guide/pull/374) on giving and receiving code reviews.
```

2022-05-30 10:18 UTC, mpadge commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +  - Maëlle Salmon
Done, thanks

2022-05-30 10:27 UTC, mpadge commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +We have updated our guidance on package evolution to include a new section on [package archiving](file:///data/mega/code/forks/dev_guide/_book/evolution.html#archivalguidance). This section reflects
Thanks, fixed now.

2022-05-30 11:03 UTC, mpadge commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +description: "Updates in version 0.8.0 of the online book 'rOpenSci Packages: Development, Maintenance, and Peer Review rOpenSci Packages: Development, Maintenance, and Peer Review'"
The problem is i think that description is already at the upper limit of typical description length. I was curious about that, so even did a quantiative look ("n" is number of characters, red line is description here):
![desc](https://user-images.githubusercontent.com/6697851/170978867-763427b0-ca3d-40e9-8eeb-13ff4acd8519.png)

I think the description as is would have to stay, and that would suggest that adding anything further would really push it beyond typical lengths. Thoughts?

2022-05-30 11:06 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +description: "Updates in version 0.8.0 of the online book 'rOpenSci Packages: Development, Maintenance, and Peer Review rOpenSci Packages: Development, Maintenance, and Peer Review'"
Yes it has a limit for e.g. Twitter cards but the end of the description could be removed as it's less informative? Fine to leave as is though. Thanks for the graph :nerd_face:

2022-06-03 13:36 UTC, maelle requested changes
Thanks so much, fantastic work!

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +rOpenSci Software Peer Review's guidance is gathered in [an online book](https://devguide.ropensci.org/) that keeps improving!
```suggestion
rOpenSci Software Peer Review's guidance is gathered in an [online book](https://devguide.ropensci.org/) that keeps improving!
```

I think this makes the link text more useful

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +This blog post summarises what's new in our Dev Guide 0.8.0, with all changes listed [in the changelog](https://devguide.ropensci.org/booknews.html).
```suggestion
This blog post summarises what's new in our Dev Guide 0.8.0, with all changes listed in the [changelog](https://devguide.ropensci.org/booknews.html).
```

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +After many years of fabulous contributions to the rOpenSci community, Stefanie Butland [left the role of community manager](/blog/2022/01/14/msg-from-stefanie/) at the start of 2022. The Dev Guide in
I was thinking we might actually not want to add any name, but have the generic phrases linked to the about page.

In general I tend to like mentioning roles rather than people :thinking:

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +This version of the Dev Guide reflects the recent expansion of our peer-review system to include statistical software. The [*Aims and Scope* section](https://devguide.ropensci.org/policies.html#aims-
```suggestion
This version of the Dev Guide reflects the recent expansion of our peer-review system to include [statistical software](/stat-software-review/). The [*Aims and Scope* section](https://devguide.ropensci.org/policies.html#aims-and-scope) now explains that statistical software is also within scope, and links directly to the [*Statistical Software Dev Guide*](https://stats-devguide.ropensci.org).
```

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +- Planning a submission or pre-submission enquiry
```suggestion
- Planning a submission or pre-submission enquiry (at what stage of the package lifecycle should it be submitted)
```

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +- Preparing for submission
```suggestion
- Preparing for submission (practical steps)
```

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +- The submission process
The other two items could also get explanations

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +Our [automation processes](/commcalls/2021-12-07) continue to ease the burden on all those involved in our software peer review system. This version of the Dev Guide can happily jettison an entire "a
```suggestion
Our [automation processes](/blog/2022/05/31/chatops-review-system-github/) continue to ease the burden on all those involved in our software peer review system. This version of the Dev Guide can happily jettison an entire "approval comment template" that reviewers used to have to copy-and-paste into an issue. That template is now automatically inserted by the `@ropensci-review-bot` as soon as a submission is approved. As described above, authors can now also call `check package` directly in a GitHub review thread. 

Our [*Continuous Integration Best Practices* chapter](https://devguide.ropensci.org/ci.html) now states that all packages are checked on submission by our own internal [`pkgcheck` system](https://docs.ropensci.org/pkgcheck), and that this system is also available as [a GitHub action](/blog/2022/02/01/pkgcheck-action/) which authors are encouraged to use prior to submission. That section now also includes a general description of GitHub actions.
```

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +While not exactly an automation enhancement, our review template now explicitly states that reviewers can download a local copy, and complete a review either as an Rmarkdown (`.Rmd`) or plain markdow
```suggestion
While not exactly an automation enhancement, our review template now explicitly states that reviewers can download a local copy, and complete a review either as an Rmarkdown (`.Rmd`) or plain markdown (`.md`) document, and simply copy-and-paste into the GitHub issue to complete the review. We are indebted to [Hugo Gruson for that clarificiation](https://github.com/ropensci/dev_guide/pull/375).
```

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +Having a contributing file [is compulsory for rOpenSci packages](https://devguide.ropensci.org/collaboration.html?q=contributing#contributing-guide), and is automatically checked by our automated pac
```suggestion
Having a contributing file is [compulsory for rOpenSci packages](https://devguide.ropensci.org/collaboration.html?q=contributing#contributing-guide), and is automatically checked by our automated package checks. We've updated our [recommendations for CONTRIBUTING.md files](https://devguide.ropensci.org/collaboration.html#contributing-guide) to suggest a number of explicit approaches, including the one-line `usethis::use_tidy_contributing()` function, and links to two more extensive examples of contributing guides. We now also recommend the inclusion of a lifecycle statement in package contributing guides, to give contributors an understanding of the likely future development of a package.
```

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +In response to [an idea from Klaus Vigo](https://github.com/ropensci/dev_guide/issues/388), the [section of package authorship](https://devguide.ropensci.org/building.html#authorship) now has an addi
```suggestion
In response to an [idea from Klaus Vigo](https://github.com/ropensci/dev_guide/issues/388), the [section of package authorship](https://devguide.ropensci.org/building.html#authorship) now has an additional section describing how to acknolwedge additional authors of external code included in a package.
```

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +In response to [an idea from Klaus Vigo](https://github.com/ropensci/dev_guide/issues/388), the [section of package authorship](https://devguide.ropensci.org/building.html#authorship) now has an addi
Btw is there a link to https://r-pkgs.org/license.html in the dev guide?

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +Standard rOpenSci practice is to acknowledge package reviewers in your DESCRIPTION file by including their names with a `role = "rev"` identifier (subject to their approval). This used to raise notes
```suggestion
Standard rOpenSci practice is to [acknowledge package reviewers in your DESCRIPTION file](/blog/2018/03/16/thanking-reviewers-in-metadata/) by including their names with a `role = "rev"` identifier (subject to their approval). This used to raise notes in CRAN package checks on older versions of R. That is thankfully no longer the case, and we are happy to have finally been able to remove that statement. Everybody can now simply insert `role = "rev"` to acknowledge all reviewers, and all CRAN systems will happily recognise those statements.
```

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +We have updated our guidance on package evolution to include a new section on [package archiving](https://devguide.ropensci.org/evolution.html#archivalguidance). This section reflects our updated pol
```suggestion
We have updated our guidance on package evolution to include a new section on [package archiving](https://devguide.ropensci.org/evolution.html#archivalguidance). This section reflects our updated policies that archived packages should move README.md to an alternative location, and reduce the main README.md to a minimal form explaining only that the package has been archived, and linking to the former README.md contents.
```

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +The [*Citation* guidelines](https://devguide.ropensci.org/building.html#citation-file) now suggest using [the `cffr` package](https://docs.ropensci.org/cffr/) to create a "CITATION.cff" file.
```suggestion
The [*Citation* guidelines](https://devguide.ropensci.org/building.html#citation-file) now suggest using [the `cffr` package](/blog/2021/11/23/cffr/) to create a "CITATION.cff" file.
```

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +The [*Recommanded Scaffolding* section of the *Packaging Guide* chapter](https://devguide.ropensci.org/building.html#recommended-scaffolding) now includes explicit recommendation of spatial packages,
```suggestion
The [*Recommanded Scaffolding* section of the *Packaging Guide* chapter](https://devguide.ropensci.org/building.html#recommended-scaffolding) now includes explicit recommendation of spatial packages, and details of (soon-to-be) obsolete spatial packages. 

The section in that chapter on [`roxygen2` use in documentation](https://devguide.ropensci.org/building.html#roxygen2-use) also describes the `@seealso` and `@family` tags for grouping functions in package documentation sites.
```

2022-06-03 13:36 UTC, maelle commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +The [section in the *Collaboration Guide* Chapter](https://devguide.ropensci.org/collaboration.html#gitflow) on "Working with collaborators" has been streamlined, with [additional links](https://gith
The post lacks a conclusion.

2022-06-03 15:52 UTC, steffilazerte reviewed
Hi Mark, looks good, just a couple of minor comments. Also the tags are different than most dev guide posts, but I don't have an opinion on whether or not that matters (see below).

* [X] post follows Content Guidelines
* [X] post follows Style Guide
* [X] title is in Title Case
* [X] publication date is ok **-> Can go to June 6th, if you prefer!**
* [X] alternative text of images is informative
* [X] Twitter metadata looks ok (paste post preview link in [Twitter card validator](https://cards-dev.twitter.com/validator); might have to click twice on "Preview card")
* [X] author metadata is provided with correct folder name
* [X] html not included in pull request of Rmd post
* [X] I ran `roblog::ro_lint_md()` on index.md
* [X] I ran `roblog::ro_check_urls()` on index.md
* [X] I ran a spell-check on index.md
* [X] YAML subject tags are ok ("tech notes" for tech notes; "community" for non-staff non-editor)
    * Normally the dev guide updates only used `dev guide` and `Software Peer Review`, but I have no opinion on whether this matters (https://ropensci.org/tags/dev-guide/)

2022-06-03 15:52 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +The [*Editors Guide* Chapter](https://devguide.ropensci.org/editorguide.html) now includes an additional section on "Answering Reviewers Questions", with links to a few previous reviews in which edit
```suggestion
The [*Editors' Guide* Chapter](https://devguide.ropensci.org/editorguide.html) now includes an additional section on "Answering Reviewers' Questions", with links to a few previous reviews in which editors have worked with reviewers and package authors to implement major package changes prior to ultimate acceptance.
```

2022-06-03 15:52 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +While not exactly an automation enhancement, our review template now explicitly states that reviewers can download a local copy, and complete a review either as an Rmarkdown (`.Rmd`) or plain markdow
Haha! Good catch!

2022-06-03 15:52 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +In addition to the automation advances described above, this release of the Dev Guide has also been eased through automation, notably through collecting several scripts and helper functions in [a new
```suggestion
In addition to the automation advances described above, this release of the Dev Guide has also been eased through automation, notably through collecting several scripts and helper functions in a new R package, [`devguider`](https://github.com/ropensci-org/devguider). One function, `prerelease_checklist()`, collects all current issues on the [Dev Guide GitHub repository](https://github.com/ropensci/dev_guide/issues) that are associated with the upcoming release, adds then to our [pre-release checklist](https://devguide.ropensci.org/bookreleaseissue.html), and opens a new GitHub issue with all of those items as a checklist used to guide the next release. This checklist also contains explicit instructions on using other functions from the `devguider` package.
```

2022-06-03 15:52 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +## Guidance on contributing.md files
```suggestion
## Guidance on `contributing.md` files
```
For clarity?

2022-06-03 15:52 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +The [*Citation* guidelines](https://devguide.ropensci.org/building.html#citation-file) now suggest using [the `cffr` package](https://docs.ropensci.org/cffr/) to create a "CITATION.cff" file.
Should this be a bulleted list?

2022-06-03 15:52 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +The [section in the *Collaboration Guide* Chapter](https://devguide.ropensci.org/collaboration.html#gitflow) on "Working with collaborators" has been streamlined, with [additional links](https://gith
agreed :grin:

2022-06-03 15:52 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +In response to [an idea from Klaus Vigo](https://github.com/ropensci/dev_guide/issues/388), the [section of package authorship](https://devguide.ropensci.org/building.html#authorship) now has an addi
```suggestion
In response to [an idea from Klaus Vigo](https://github.com/ropensci/dev_guide/issues/388), the [section of package authorship](https://devguide.ropensci.org/building.html#authorship) now has an additional section describing how to acknowledge additional authors of external code included in a package.
```

2022-06-03 15:52 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +## Two-Factor Autentication now required
```suggestion
## Two-Factor Authentication now required
```

2022-06-07 08:49 UTC, mpadge commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +The [*Citation* guidelines](https://devguide.ropensci.org/building.html#citation-file) now suggest using [the `cffr` package](https://docs.ropensci.org/cffr/) to create a "CITATION.cff" file.
Done, thanks

2022-06-07 08:58 UTC, mpadge commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +The [section in the *Collaboration Guide* Chapter](https://devguide.ropensci.org/collaboration.html#gitflow) on "Working with collaborators" has been streamlined, with [additional links](https://gith
Conclusion done, thanks! Sorry, i completely missed that somehow :confused:

2022-06-07 09:01 UTC, mpadge commented
@maelle @steffilazerte I've requested re-reviews from both of you. As soon as you have both approved, I'll align the dates on the `content/blog` sub-folder and merge, if that's okay with both of you? Hopefully the timing works, with @maelle away until Wed or so, and @steffilazerte away from Wed onwards. Thanks both of you!

2022-06-07 14:26 UTC, steffilazerte reviewed
Awesome 😁  I have some more nit-picky comments regarding formatting consistency (i.e. using `` around all file names), but I leave it up to you to decide whether that's necessary.

2022-06-07 14:26 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +After many years of fabulous contributions to the rOpenSci community, Stefanie Butland [left the role of community manager](/blog/2022/01/14/msg-from-stefanie/) at the start of 2022. The Dev Guide in
```suggestion
After many years of fabulous contributions to the rOpenSci community, Stefanie Butland [left the role of community manager](/blog/2022/01/14/msg-from-stefanie/) at the start of 2022. The Dev Guide included several references to Stefanie, particularly regarding preparing blog posts, as well as preparing Dev Guide releases. Her name has been removed and replaced with a generic "*Community Manager*" title.
```

2022-06-07 14:26 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +## Guidance on `contributing.md` files
Missed this the first time, should this be all caps? i.e., 
```suggestion
## Guidance on `CONTRIBUTING.md` files
```

2022-06-07 14:26 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +Standard rOpenSci practice is to [acknowledge package reviewers in your DESCRIPTION file](/blog/2018/03/16/thanking-reviewers-in-metadata/) by including their names with a `role = "rev"` identifier (
```suggestion
Standard rOpenSci practice is to [acknowledge package reviewers in your `DESCRIPTION` file](/blog/2018/03/16/thanking-reviewers-in-metadata/) by including their names with a `role = "rev"` identifier (subject to their approval). This used to raise notes in CRAN package checks on older versions of R. That is thankfully no longer the case, and we are happy to have finally been able to remove that statement. Everybody can now simply insert `role = "rev"` to acknowledge all reviewers, and all CRAN systems will happily recognise those statements.
```

2022-06-07 14:26 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +We have updated our guidance on package evolution to include a new section on [package archiving](https://devguide.ropensci.org/evolution.html#archivalguidance). This section reflects our updated pol
```suggestion
We have updated our guidance on package evolution to include a new section on [package archiving](https://devguide.ropensci.org/evolution.html#archivalguidance). This section reflects our updated policies that archived packages should move `README.md` to an alternative location, and reduce the main `README.md` to a minimal form explaining only that the package has been archived, and linking to the former `README.md` contents.
```

2022-06-07 14:26 UTC, steffilazerte commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +- The [*Citation* guidelines](https://devguide.ropensci.org/building.html#citation-file) now suggest using [the `cffr` package](/blog/2021/11/23/cffr/) to create a "CITATION.cff" file.
```suggestion
- The [*Citation* guidelines](https://devguide.ropensci.org/building.html#citation-file) now suggest using [the `cffr` package](/blog/2021/11/23/cffr/) to create a `CITATION.cff` file.
```

2022-06-07 17:31 UTC, mpadge commented on content/blog/2022-06-09-devguide-0.8.0/index.md
> +## Guidance on `contributing.md` files
No, because all previous mentions in other posts have been uniformly lower case, so this retains that consistency.

2022-06-07 17:35 UTC, mpadge commented
Thanks Steffi, I had adopted formats from previous posts and dumped all backticks, but happy to have them reinserted. All tweaks and format issues  for new community manager to systematise...

2022-06-09 06:12 UTC, maelle commented
Ah yeah it's really annoying how often I've had to restart deploys manually lately, it's making me consider looking for an alternative for PR deploy previews... Anyhow it's worked!

2022-06-09 07:40 UTC, merged