English blog post on how to contribute
ropensci/roweb3 pull request #385
Opened 2022-09-07 13:56 UTC by yabellini

English version on the blog post on how to contribute to rOpenSci.  I will translate to Spanish when we agree on the English version.

2022-09-08 06:58 UTC, maelle requested changes
Thank you, this will be a super useful post!

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +tweet: "Are you curious about @rOpenSci? Do you wonder where I get started participating? 🤔 Glad you asked! A summary on how to get involved with us!"
```suggestion
tweet: "Are you curious about @rOpenSci? Wondering how to start participating? 🤔 Glad you asked! A summary on how to get involved with us!" 
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +title: How to get involved with rOpenSci
I wonder whether we should rather use "participate" (not sure).

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +
```suggestion
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +
```suggestion
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Discussion forum](https://discuss.ropensci.org/): public forum on Discourse for use cases, Q & A about rOpenSci packages, exploration of ideas and best practices
Maybe link to https://ropensci.org/blog/2022/01/11/ropensci-forum/

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Technical Notes](https://ropensci.org/technotes/): browse our technical notes to see packages updates, how-to and examples.
Maybe rather link to the blog in general?

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +## Asking for Help
```suggestion
## Finding information & asking for Help
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Community Calls](https://discuss.ropensci.org/): join to our quarterly Community Calls, these are free and open for anyone to attend and provide an opportunity to connect with rOpenSci community m
```suggestion
* [Community Calls](/commcalls): join to our quarterly Community Calls, these are free and open for anyone to attend and provide an opportunity to connect with rOpenSci community members around the world.
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Remote Co-Working Sessions](https://ropensci.org/blog/2021/08/17/coworking-sessions/): monthly social coworking + office hours sessions via Zoom
```suggestion
* [Remote Co-Working Sessions](/blog/2021/08/17/coworking-sessions/): monthly social coworking + office hours sessions via Zoom
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [The R-universe](https://ropensci.org/r-universe/): improving publication and discovery of research software in R.
```suggestion
* [The R-universe](/r-universe/): improving publication and discovery of research software in R.
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Packages](https://ropensci.org/packages/): our packages are carefully vetted, staff- and community-contributed R software tools that in particular lower barriers to working with local and remote s
```suggestion
* [Packages](/packages/): our packages are carefully vetted, staff- and community-contributed R software tools that in particular lower barriers to working with local and remote scientific data sources.
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Package Review](https://ropensci.org/software-review/): packages contributed by the community undergo a transparent, constructive, non-adversarial and open review process.
```suggestion
* [Software Peer-Review](/software-review/): packages contributed by the community undergo a transparent, constructive, non-adversarial and open review process.
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Packages Statistical Review](https://ropensci.org/stat-software-review/): we have expanded our peer review system to include packages that implement statistical algorithms.
```suggestion
* [Statistical Software Peer-Review](/stat-software-review/): we have expanded our peer review system to include packages that implement statistical algorithms.
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Multilingual Publishing](https://ropensci.org/blog/2021/12/20/inclusive-leadership-program/): we are expanding documentation for our review process beyond the English language.
```suggestion
* [Multilingual Publishing](/blog/2021/12/20/inclusive-leadership-program/): we are expanding documentation for our review process beyond the English language.
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Champions Program](https://ropensci.org/blog/2021/12/20/inclusive-leadership-program/): support community champions from historically excluded groups to become contributors to rOpenSci.
```suggestion
* [Champions Program](/blog/2021/12/20/inclusive-leadership-program/): support community champions from historically excluded groups to become contributors to rOpenSci.
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Package Citations](https://ropensci.org/citations/): We manually curate a dataset of all citations of our packages. If you use one of our packages, please cite it (learn here how).
I would not mention this as it is currently not curated.

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Package Citations](https://ropensci.org/citations/): We manually curate a dataset of all citations of our packages. If you use one of our packages, please cite it (learn here how).
But at the same time it is always good to encourage citations, so linking to https://ropensci.org/blog/2021/11/16/how-to-cite-r-and-r-packages/ would be nice.

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Help Wanted](https://ropensci.org/help-wanted/): if you are ready to contribute, here is a list of issues where your expertise is needed (we have issues for different levels of expertise).
```suggestion
* [Help Wanted](/help-wanted/): if you are ready to contribute, here is a list of issues where your expertise is needed (we have issues for different levels of expertise).
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Talks and Publications](https://ropensci.org/talks-papers/): talks by the rOpenSci team or community members representing us, in English, French, or Spanish.
```suggestion
* [Talks and Publications](/talks-papers/): talks by the rOpenSci team or community members representing us, in English, French, or Spanish.
```

2022-09-08 06:58 UTC, maelle commented on content/blog/2022-09-08-contributing/index.md
> +* [Blog](https://ropensci.org/blog/): articles written by our community. Our [guide explains how to contribute a blog post](https://blogguide.ropensci.org/).
```suggestion
* [Blog](/blog/): articles written by our community. Our [guide explains how to contribute a blog post](https://blogguide.ropensci.org/).
```

2022-09-08 10:25 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +* [Package Citations](https://ropensci.org/citations/): We manually curate a dataset of all citations of our packages. If you use one of our packages, please cite it (learn here how).
```suggestion
* [Package Citations](/citations/): If you use one of our packages, please cite it! [You can learn here how to cite R and R Packages](https://ropensci.org/blog/2021/11/16/how-to-cite-r-and-r-packages/).
```

2022-09-08 10:29 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +* [Discussion forum](https://discuss.ropensci.org/): public forum on Discourse for use cases, Q & A about rOpenSci packages, exploration of ideas and best practices
```suggestion
* [Discussion forum](https://discuss.ropensci.org/): public forum on Discourse for use cases, Q & A about rOpenSci packages, exploration of ideas, and best practices. Learn [how to gather on the rOpenSci forum](/blog/2022/01/11/ropensci-forum/)
```

2022-09-08 10:29 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +title: How to get involved with rOpenSci
```suggestion
title: How to participate with rOpenSci 
```

2022-09-08 10:34 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +* [Technical Notes](https://ropensci.org/technotes/): browse our technical notes to see packages updates, how-to and examples.
```suggestion
* [Blog](/blog/): browse our technical notes to see packages updates, how-to and examples. You can find articles written by our community members. If you feel inspired, our [guide explains how to contribute a blog post](https://blogguide.ropensci.org/).
```

2022-09-08 10:35 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +
* [Talks and Publications](/talks-papers/): talks by the rOpenSci team or community members representing us, in English, French, or Spanish.

2022-09-08 10:35 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +## Additional Resources
```suggestion

```

2022-09-08 10:36 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +* [Talks and Publications](/talks-papers/): talks by the rOpenSci team or community members representing us, in English, French, or Spanish.
```suggestion

```

2022-09-08 10:36 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +* [Blog](/blog/): articles written by our community. Our [guide explains how to contribute a blog post](https://blogguide.ropensci.org/).
```suggestion

```

2022-09-08 10:38 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +
```suggestion
* [Talks and Publications](https://github.com/talks-papers/): talks by the rOpenSci team or community members representing us, in English, French, or Spanish.
```

2022-09-08 14:00 UTC, steffilazerte reviewed
Hi @yabellini 

Looks lovely! I've been opinionated about some things, feel free to ignore (I don't mind :grin:). There are a couple of stylistic things (title should be title case, section headings in sentence case) that I've tweaked but generally not much.

Thanks!

* [X] post follows Content Guidelines
* [ ] post follows Style Guide
* [ ] title is in Title Case
* [ ] publication date is ok
* [X] alternative text of images is informative
* [X] Twitter metadata looks ok (paste post preview link in [Twitter card validator](https://cards-dev.twitter.com/validator); might have to click twice on "Preview card")
* [X] author metadata is provided with correct folder name
* [X] html not included in pull request of Rmd post
* [X] I ran `roblog::ro_lint_md()` on [index.md](http://index.md/)
* [X] I ran `roblog::ro_check_urls()` on [index.md](http://index.md/)
* [X] I ran a spell-check on [index.md](http://index.md/)
* [X] YAML subject tags are ok ("tech notes" for tech notes; "community" for non-staff non-editor)

2022-09-08 14:13 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +
Yes, agree we need a close for the blog post.

2022-09-08 19:29 UTC, steffilazerte commented on content/blog/2022-09-08-contributing/index.md
> +* [Talks and Publications](https://github.com/talks-papers/): talks by the rOpenSci team or community members representing us, in English, French, or Spanish.
Just realized that this link doesn't exist... not sure what it should be though!

2022-09-08 19:29 UTC, steffilazerte commented
One more comment about a broken link, sorry I missed it before!

2022-09-12 10:53 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +* [Talks and Publications](https://github.com/talks-papers/): talks by the rOpenSci team or community members representing us, in English, French, or Spanish.
```suggestion
* [Talks and Publications](https://ropensci.org/talks-papers/): talks by the rOpenSci team or community members representing us, in English, French, or Spanish.
```

2022-09-12 11:00 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +
## Ready to contribute!

We are happy you made it this far.  We hope you find some way to participate in the options.  We would be glad to learn more if you have ideas about other ways to collaborate with us.

We hope to see you in some of our spaces.

2022-09-12 11:01 UTC, yabellini commented on content/blog/2022-09-08-contributing/index.md
> +
```suggestion
## Ready to contribute!

We are happy you made it this far.  We hope you find some way to participate in the options.  We would be glad to learn more if you have ideas about other ways to collaborate with us.

We hope to see you in some of our spaces.
```

2022-09-12 11:03 UTC, yabellini commented
Thanks so much Steffi, I think I should change the date and then we are ok?

2022-09-12 18:56 UTC, steffilazerte commented on content/blog/2022-09-08-contributing/index.md
> +We are happy you made it this far.  We hope you find some way to participate in the options.  We would be glad to learn more if you have ideas about other ways to collaborate with us.
```suggestion
We are happy you made it this far.  We hope you find some way to participate among these options.  We would be glad to learn more if you have ideas about other ways to collaborate with us!
```

2022-09-12 18:56 UTC, steffilazerte commented on content/blog/2022-09-08-contributing/index.md
> +* [Package Citations](/citations/): If you use one of our packages, please cite it! [You can learn here how to cite R and R Packages](/blog/2021/11/16/how-to-cite-r-and-r-packages/).
```suggestion
* [Package Citations](/citations/): if you use one of our packages, please cite it! [You can learn here how to cite R and R Packages](/blog/2021/11/16/how-to-cite-r-and-r-packages/).
```

2022-09-12 18:56 UTC, steffilazerte commented on content/blog/2022-09-08-contributing/index.md
> +* _Social Media_: Follow our organization’s activities on [Twitter](https://twitter.com/rOpenSci), and [Vimeo](https://vimeo.com/ropensci). Also follow our [roknowtifier bot](https://twitter.com/rokn
```suggestion
* _Social Media_: follow our organization’s activities on [Twitter](https://twitter.com/rOpenSci), and [Vimeo](https://vimeo.com/ropensci). Also follow our [roknowtifier bot](https://twitter.com/roknowtifier) that tweets new rOpenSci packages or new versions of packages
```

2022-09-12 18:56 UTC, steffilazerte commented on content/blog/2022-09-08-contributing/index.md
> +* [Packages Documentation](https://docs.ropensci.org/): This site hosts pkgdown documentation for all rOpenSci packages.
```suggestion
* [Packages Documentation](https://docs.ropensci.org/): this site hosts pkgdown documentation for all rOpenSci packages.
```

2022-09-12 18:57 UTC, steffilazerte commented
Yup! Just a couple of last nit picky formating and one wording suggestion, other than that, pick at date (don't forget to change both the folder date and the YAML date), and we're good to go!

2022-09-13 18:39 UTC, yabellini commented
The translation is ready too, so if you think is ok we can publish both languages.

2022-09-13 19:18 UTC, steffilazerte commented on content/blog/2022-09-13-contributing/index.md
> +[Entrada en español](/blog/2022/09/13/contributing-es/)
```suggestion
[Entrada en español](/blog/2022/09/13/contributing-ropensci-es/)
```

2022-09-13 19:18 UTC, steffilazerte commented on content/blog/2022-09-13-contributing-es/index.md
> +[Post in English](/blog/2022/09/13/contributing-es/)
```suggestion
[Post in English](/blog/2022/09/13/contributing-ropensci/)
```

2022-09-13 19:20 UTC, steffilazerte commented
The English / español links need to be adjusted (see my suggestions) but other than that I'd publish!

2022-09-13 19:21 UTC, steffilazerte commented on content/blog/2022-09-13-contributing-es/index.md
> +title: Cómo participar en rOpenSci
```suggestion
title: Cómo Participar en rOpenSci
```

2022-09-13 19:23 UTC, yabellini commented on content/blog/2022-09-13-contributing-es/index.md
> +title: Cómo participar en rOpenSci
In Spanish we don't capitalize words in titles. If we need it now I'm ok but we should change that rule for spanish

2022-09-13 19:24 UTC, steffilazerte commented on content/blog/2022-09-13-contributing-es/index.md
> +title: Cómo participar en rOpenSci
Oh that makes sense, I was wondering. I think it makes sense to have different style guides for different languages.

2022-09-13 19:26 UTC, yabellini commented
Thanks for spot the wrong links! I commit those changes. For the title we can change for this one but un Spanish we don't capitalize words in titles. Only the first one (and mames).

2022-09-13 19:27 UTC, steffilazerte commented
I wouldn't change the title then, keep it how it should be in Spanish. Our current style guide makes sense for English but not for Spanish!

2022-09-13 19:28 UTC, yabellini commented
Then we are ready to go!

2022-09-13 19:51 UTC, merged