Champion program blog
ropensci/roweb3 pull request #390
Opened 2022-09-17 21:57 UTC by yabellini

* [ ] I have read the Content Guidelines.
* [ ] I have read the Technical Guidelines.
* [ ] I used or followed the R Markdown or Markdown template.
* [ ] I have followed the Style Guide.
* [ ] I created or updated my author metadata with correct folder name.
* [ ] I have added relevant tags after browsing existing tags (including "community" tag).
* [ ] I have added the "tech notes" tag if this is a technote.
* [ ] I ran `roblog::ro_lint_md()` on index.md (optional).
* [ ] I ran `roblog::ro_check_urls()` on index.md (optional).
* [ ] I ran a spell-check on index.md.

2022-09-17 21:59 UTC, yabellini commented
Some questions:
- Do we should create a tag "champions program"?
- I would like to use some of the picture representing our community members on the blog post.  What do you think? 

Clarification:
- I will translate to Spanish when we agree on the English text, but I create the placeholder for the blog post.

2022-09-19 06:21 UTC, maelle commented
>  Do we should create a tag "champions program"?

Good idea, and we could add it to the CZI funding announcement?

>  I would like to use some of the picture representing our community members on the blog post. What do you think?

You mean past unconf photos? I'm not sure we have a definite list of them but there are some in past unconf blog posts. Another idea would be screenshots of comm calls.

2022-09-19 06:28 UTC, maelle requested changes
Thank you!!

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +
Should there be a short intro? Not sure

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +At rOpenSci, we recognize that there is a dismaying lack of diversity in the ecosystem of research software and open source communities. The R Community is no exception; its developers are overwhelmi
```suggestion
At rOpenSci, we recognize that there is a dismaying lack of diversity in the ecosystem of research software and open source communities. The R Community is no exception; its developers are overwhelmingly white, male, and from a handful of countries. That appalling lack of diversity is potentially detrimental to the sustainability, utility and productivity of projects. 
```

just to underline again we find this lack of diversity very wrong

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +### What is our champions program like?
```suggestion
### What is our champions program?
```

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +We have developed a 12-month-long cohort-based training and personal mentorship program. Champions will participate in a 6-week long cohort-based training on a) planning and facilitating engaging and
```suggestion
We have developed a **12-month-long program including cohort-based training and personal mentorship**. Champions will participate in a 6-week long cohort-based training on a) planning and facilitating engaging and inclusive workshops to support participants’ success, b) knowledge of various channels through which new members can engage in and contribute to rOpenSci and R projects, and c) technical skills in software development and review. 
```

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +We have developed a 12-month-long cohort-based training and personal mentorship program. Champions will participate in a 6-week long cohort-based training on a) planning and facilitating engaging and
This way it is clearer the training is not 12 month long

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +After training, Champions will develop their project, which can be one of these options: create a new package, take over the maintenance of an existing rOpenSci package, go through the review process
```suggestion
After training, Champions will develop their project, which can be one of these options: 

- create a new package, take over the maintenance of an existing rOpenSci package, 
- go through the review process with an R package they already have developed, 
- or be a reviewer on our peer review system.  

Other Champions activities include the chance to deliver a talk, write blog posts and teach other community members. During this stage, they will receive personal and group mentorship through meetings with mentors, quarterly cohort calls, Community Manager support, and a dedicated channel on rOpenSci Slack workspace.
```

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +You can see all details on our [Champions Program webpage](/champions/)
```suggestion
You can see all details on our [Champions Program webpage](/champions/).
```

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +### How to apply
```suggestion
### How to apply?
```

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +## We are thrilled to launch our Champions program!
this could be the introduction and this way all the h3 in the remainder of the post (`###`) could become h2 (`##`). 

```suggestion
> We are thrilled to launch our Champions program!
```

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +|Nov 1, 2022|Special co-working hours|
link?

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +Please, contact our Community Manager [by email](mailto: yabellini@ropensci.org).
```suggestion
Please, contact our Community Manager [by email](mailto:yabellini@ropensci.org). 
```

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +## We look forward to meeting all of you passionate Champions out there :)
```suggestion
We look forward to meeting all of you passionate Champions out there :)
```

2022-09-19 06:28 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +## We look forward to meeting all of you passionate Champions out there :)
Also I am in favor of smileys with noses :-D :o) ;-) but it's not important :joy:

2022-09-19 10:24 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +At rOpenSci, we recognize that there is a dismaying lack of diversity in the ecosystem of research software and open source communities. The R Community is no exception; its developers are overwhelmi
I used _appalling_ in my first version and was requested to look for other options.  I'm ok with adding another word that helps with that message, but here my vocabulary is short.

2022-09-19 10:28 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +|Nov 1, 2022|Special co-working hours|
I don't have the Airtable form yet.  I will add it when we build it. The template is ready on the champions space on the website. I have that link.

2022-09-19 10:30 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +- create a new package, take over the maintenance of an existing rOpenSci package,
```suggestion
- create a new package, 
- take over the maintenance of an existing rOpenSci package, 
```

2022-09-19 10:30 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +We look forward to meeting all of you passionate Champions out there :)
```suggestion
We look forward to meeting all of you passionate Champions out there :-D
```

2022-09-19 10:33 UTC, yabellini commented
Thanks so much for the review, @maelle :-) . I added the nose to the smile ;-)
About the pictures, I mean the drawing of our collaborators, the ones that are on the front cover of the contribution guide, and the ones also appear on the bottom of our webpage in hex sticker form. I found those pictures, so I will try to add them to the blog post.

2022-09-19 18:38 UTC, steffilazerte reviewed
Hi @yabellini I am so excited for this!

See what you think of my suggestions! Generally speaking looks great!

* [X] post follows Content Guidelines
* [X] post follows Style Guide
* [X] title is in Title Case
* [X] publication date is ok
* [X] alternative text of images is informative
* [X] Twitter metadata looks ok (paste post preview link in [Twitter card validator](https://cards-dev.twitter.com/validator); might have to click twice on "Preview card")
* [X] author metadata is provided with correct folder name
* [X] html not included in pull request of Rmd post
* [X] I ran `roblog::ro_lint_md()` on index.md
* [X] I ran `roblog::ro_check_urls()` on index.md
* [X] I ran a spell-check on index.md
* [ ] YAML subject tags are ok ("tech notes" for tech notes; "community" for non-staff non-editor)

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +At rOpenSci, we recognize that there is a dismaying lack of diversity in the ecosystem of research software and open source communities. The R Community is no exception; its developers are overwhelmi
```suggestion
At rOpenSci, we recognize that there is a dismaying lack of diversity in the ecosystem of research software and open source communities. The R Community is no exception; its developers are overwhelmingly white, male, and from a handful of countries. This disappointing lack of diversity is potentially detrimental to the sustainability, utility and productivity of projects. 
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +rOpenSci Champion Program [is part of a series of activities and projects we are carrying out to ensure our research software serves everyone in our communities](https://ropensci.org/blog/2021/12/20/
```suggestion
The rOpenSci Champion Program [is part of a series of activities and projects we are carrying out to ensure our research software serves everyone in our communities](/blog/2021/12/20/inclusive-leadership-program/), which means that it needs to be sustainable and open, and built by and for all groups.
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +That is why this program focuses __on people who belong to groups that are historically and systematically excluded__ from the open software and research software communities and who are interested i
```suggestion
That is why this program focuses on __people who belong to groups that are historically and systematically excluded__ from the open software and research software communities and who are interested in contributing to rOpenSci and the broader open source and research software communities.
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +We have developed a **12-month-long program including cohort-based training and personal mentorship**. Champions will participate in a 6-week long cohort-based training on a) planning and facilitatin
```suggestion
We have developed a **12-month-long program including cohort-based training, project development, and personal mentorship**. 

Champions will participate in a 6-week long cohort-based training on a) planning and facilitating engaging and inclusive workshops to support participants’ success, b) knowledge of various channels through which new members can engage in and contribute to rOpenSci and R projects, and c) technical skills in software development and review. 
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +- or be a reviewer on our peer review system.
```suggestion
- or be a reviewer for our peer review system.  
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +Other Champions activities include the chance to deliver a talk, write blog posts and teach other community members. During this stage, they will receive personal and group mentorship through meeting
```suggestion
Other Champions activities include options for delivering a talk, writing blog posts and teaching other community members. During this stage, Champions will receive personal and group mentorship through meetings with mentors, quarterly cohort calls, Community Manager support, and a dedicated channel on rOpenSci Slack workspace.
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +Please, [fill out the application form]() ([this template shows the information we will require in the form]()) before __Friday, Nov 7, 2022__.
```suggestion
Please, fill out the [application form]() (this [template]() shows the information we require) before __Friday, Nov 7, 2022__.
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +|Sep 23, 2022|Call for Application opens|
```suggestion
|Sep 23, 2022|Call for Applications opens|
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +|Oct 24, 2022|Application Community Call|
```suggestion
|Oct 24, 2022|Applications Community Call|
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +|Nov 1, 2022|Special co-working hours|
```suggestion
|Nov 1, 2022|Special [co-working](/events/coworking-2022-11/) hours|
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +We will have a [Community Call on October 24]() and a [Coworking space on November 1]() to help you with your application.
```suggestion
We will have a [Community Call on October 24]() and a [Coworking space on November 1](/events/coworking-2022-11/) to help you with your application.
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +We look forward to meeting all of you passionate Champions out there :-D
```suggestion
**We look forward to meeting all of you passionate Champions out there :-D**
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +### Why a Champions Program?
```suggestion
## Why a Champions Program?
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +### What is our champions program?
```suggestion
## What is our champions program?
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +### How to apply?
```suggestion
## How to apply?
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +#### Application Timeline
```suggestion
### Application Timeline
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program-es/index.md
> +  - welcome
Definitely needs a tag, what about this one? (will become `champions-program`). There also exists the `diversity` tag?
```suggestion
  - welcome
  - diversity
  - champions program
```

2022-09-19 18:38 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program-es/index.md
> +  - welcome
(I love that I can read this as "Welcome diversity, champions program!")

2022-09-20 08:08 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +|Nov 1, 2022|Special co-working hours|
i mean to the coworking event :-)

2022-09-20 08:11 UTC, maelle commented
Before using the images we need to check the corresponding contract. :-)

2022-09-22 01:14 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +> We are thrilled to launch our Champions program!
```suggestion
> We are thrilled to launch our Champions program pilot!
```

2022-09-22 01:33 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +
We are looking for people that work in STEAM fields, from anywhere in the world, who already have development knowledge with the R language.

2022-09-22 01:33 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +
```suggestion
We are looking six to nine Champions for this first pilot. We expect to co-create the rOpenSci Champion program with the selected applicants and influence future editions with their experience and feedback.

We look forward to receiving many applications and are committed to directing non-selected applicants towards other ways in which they can contribute to rOpenSci.
```

2022-09-22 01:34 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +
```suggestion
We are looking for people that work in STEAM fields, from anywhere in the world, who already have development knowledge with the R language. 
```

2022-09-22 01:38 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +|Nov 1, 2022|Special [co-working](/events/coworking-2022-11/) hours|
```suggestion
|Nov 1, 2022| [OPTIONAL] [Co-working hours](/events/coworking-2022-11/): receive help with your application to the champions program. |
```

2022-09-22 01:39 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +|Oct 24, 2022| [OPTIONAL] Community Call| -  Tips for submitting your champions program application
```suggestion
|Oct 24, 2022| [OPTIONAL] [Community Call](/commcalls/oct2022-champions/) -  Tips for submitting your champions program application
```

2022-09-22 01:39 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +|Oct 24, 2022| [OPTIONAL] [Community Call](/commcalls/oct2022-champions/) -  Tips for submitting your champions program application
```suggestion
|Oct 24, 2022| [OPTIONAL] [Community Call](/commcalls/oct2022-champions/) -  Tips for submitting your champions program application |
```

2022-09-22 01:40 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +We will have a [Community Call on October 24]() and a [Coworking space on November 1](/events/coworking-2022-11/) to help you with your application.
```suggestion
We will have a [Community Call on October 24](/commcalls/oct2022-champions/) and a [Coworking space on November 1](/events/coworking-2022-11/) to help you with your application.
```

2022-09-22 02:19 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +## What is our champions program?
```suggestion


## What is our champions program?
```

2022-09-22 02:21 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +Please, fill out the [application form]() (this [template]() shows the information we require) before __Friday, Nov 7, 2022__.
```suggestion
Please, fill out the [application form](https://airtable.com/shrAsYlSXU0coJ5Ld) (this [template](/champions/file/champions_template.md) shows the information we require) before __Friday, Nov 7, 2022__.
```

2022-09-22 02:25 UTC, yabellini commented
Things to check if are ok (@maelle):
- link to comm call.
- link to form template (this is on a folder inside champions folder on content folder).
- link to the form.

I still have to do the translation.  It will be the first task in my morning.

2022-09-22 08:50 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +Please, fill out the [application form](https://airtable.com/shrAsYlSXU0coJ5Ld) (this [template](/champions/file/champions_template.md) shows the information we require) before __Friday, Nov 7, 2022_
```suggestion
Please, fill out the [application form](https://airtable.com/shrAsYlSXU0coJ5Ld) (this [template](/champions/file/champions_template) shows the information we require) before __Friday, Nov 7, 2022__.
```

2022-09-22 11:59 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +Please, fill out the [application form](https://airtable.com/shrAsYlSXU0coJ5Ld) (this [template](/champions/file/champions_template.md) shows the information we require) before __Friday, Nov 7, 2022_
If we remove, the .md from the name of the template, the file will open? because the preview of the webpage gives a 404 error.

2022-09-22 12:24 UTC, maelle commented on content/blog/2022-09-23-launch-champions-program/index.md
> +Please, fill out the [application form](https://airtable.com/shrAsYlSXU0coJ5Ld) (this [template](/champions/file/champions_template.md) shows the information we require) before __Friday, Nov 7, 2022_
in the webpage I had forgotten `/champions/`, this link will work.

The md file does not exist anymore in the built website actually, as Hugo renders all markdown files from content to HTML.

2022-09-22 12:27 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program/index.md
> +Please, fill out the [application form](https://airtable.com/shrAsYlSXU0coJ5Ld) (this [template](/champions/file/champions_template.md) shows the information we require) before __Friday, Nov 7, 2022_
Thanks so much :-) I'm learning a lot.

2022-09-22 13:44 UTC, steffilazerte reviewed
I've added a couple more extremely nitpicky suggestions (mostly related to consistency in capitalizations). I hope this is useful and not too tedious 😅 

I suggest referring to the program and participants as a title (i.e. Champions Program, and Champions), which is done about 90% of the time already 😄 

I also noticed two typos on the AirTable form: 

- I think "rOpenSci Champion Program" should be "**The** rOpenSci Champion**s** Program"
- "Thank you for your interest in contribute to rOpenSci community!" should be "Thank you for your interest in contribut**ing** to **the** rOpenSci community"

Can't wait for the launch! 🎉

2022-09-22 13:44 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +We are looking six to nine Champions for this first pilot. We expect to co-create the rOpenSci Champion program with the selected applicants and influence future editions with their experience and fe
```suggestion
We are looking for six to nine Champions for this first pilot. We expect to co-create the rOpenSci Champions Program with the selected applicants and influence future editions with their experience and feedback.
```

2022-09-22 13:44 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +### Application Timeline
```suggestion
### Application timeline
```

2022-09-22 13:44 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +
Need to remove empty line to fix table
```suggestion
```

2022-09-22 13:44 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +## What is our champions program?
This is where my nit-pickiness comes out in force! 

Let's use "Champions Program" as a title throughout (right now sometimes it's "Champions Program", sometimes "champions program", sometimes "Champions program"
```suggestion
## What is our Champions Program?
```

2022-09-22 13:44 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +|Oct 24, 2022| [OPTIONAL] [Community Call](/commcalls/oct2022-champions/) -  Tips for submitting your champions program application |
```suggestion
|Oct 24, 2022| [OPTIONAL] [Community Call](/commcalls/oct2022-champions/) -  Tips for submitting your Champions Program application |
```

2022-09-22 13:44 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +|Nov 1, 2022| [OPTIONAL] [Co-working hours](/events/coworking-2022-11/): receive help with your application to the champions program. |
```suggestion
|Nov 1, 2022| [OPTIONAL] [Co-working hours](/events/coworking-2022-11/): receive help with your application to the Champions Program |
```

2022-09-22 13:44 UTC, steffilazerte commented on content/blog/2022-09-23-launch-champions-program/index.md
> +|Nov 25, 2022|Communication with selected champions.|
```suggestion
|Nov 25, 2022|Communication with selected Champions |
```

2022-09-22 14:36 UTC, yabellini commented on content/blog/2022-09-23-launch-champions-program-es/index.md
> +  - champions program
```suggestion
  - champions program
  - español
  - spanish
```

2022-09-22 14:38 UTC, yabellini commented
I think this is ready to merge too.

2022-09-22 18:17 UTC, merged