Add covidpreprints post
ropensci/roweb3 pull request #43
Opened 2020-10-05 21:05 UTC by Bisaloo

2020-10-05 21:15 UTC, Bisaloo commented
Our main difficulty was to balance the content to fit both rOpenSci and preLights editorial lines. Please let us know what you think on this specific point please.

Please also don't hesitate to request big changes if necessary. We still have plenty of time to update before the planned publication date.

2020-10-05 21:16 UTC, Bisaloo commented
Is there a way to get the netlify preview or it has not been enabled on the new website yet?

2020-10-05 21:41 UTC, stefaniebutland commented
Thank you @Bisaloo.

On first look I see 
- `content/author/zhang-he-goh/_index.yml` should be `_index.md`
- after the first plot, images are not rendered 

![Screen Shot 2020-10-05 at 2 27 23 PM](https://user-images.githubusercontent.com/11927811/95135081-c32c4500-0718-11eb-9090-f0b1a858d899.png)


I will review this on Tues Oct 6.

2020-10-07 00:15 UTC, stefaniebutland requested changes
As I expected, I LOVE this post! So pleased we can cross-post with preLights. Thank you for giving rOpenSci the opportunity to share this.

The flow of the post and section headings are great. Very clear and compelling description of the project motivation, need for automation, and strong conclusion. 

In addition to the checklist below, I've made 22 comments or suggested commits. Most important for the rOpenSci audience is my request to show and/or link to some code (commented inline). I'm open to your ideas on how to address that. 

One difference in new website is main headings are ##, not ###. (We're about to merge update to our blog post templates. I'm sorry we didn't fix taht in time for you.) I'll complete my checklist after your revisions. 

* [x] post follows Content Guidelines
* [ ] post follows Style Guide
* [ ] title is in Title Case
* [x] publication date is ok
* [ ] alternative text of images is informative
* [ ] Twitter metadata looks ok (paste post preview link in [Twitter card validator](https://cards-dev.twitter.com/validator); might have to click twice on "Preview card")
* [x] author metadata is provided with correct folder name
* [x] html not included in pull request of Rmd post
* [ ] I ran `roblog::ro_lint_md()` on index.md
* [ ] I ran `roblog::ro_check_urls()` on index.md
* [ ] I ran a spell-check on index.md
* [ ] YAML subject tags are ok

2020-10-07 00:15 UTC, stefaniebutland commented on content/blog/2020-10-13-covidpreprints/index.md
> +Experts from all around the world are asking, “What have we learnt from this pandemic?” As advocates of preprints and open science, we are constantly mindful about how our project would remain releva
"long-drawn" doesn't quite sound right, but I can't think of a replacement rn

2020-10-07 00:15 UTC, stefaniebutland commented on content/blog/2020-10-13-covidpreprints/index.md
> +This project illustrates what can be achieved when different communities focused on various aspects of Open Science intercept: preLights came up with the original idea and maintains the website conte
intercept -> intersect?

2020-10-07 12:15 UTC, Bisaloo commented on content/blog/2020-10-13-covidpreprints/index.md
> +1. Get the altmetric score of each publication with the [rAltmetric](https://docs.ropensci.org/rAltmetric/) package
What do you mean? Add a footnote instead of / in addition to the link to the package page?

2020-10-07 12:26 UTC, Bisaloo commented on content/blog/2020-10-13-covidpreprints/index.md
> +Here is a quick rundown of our update process:
The code for this is a bit long/complicated (https://github.com/coatesj/covidpreprints/blob/master/vignettes/timeline.Rmd). I'll think about what we could add while still making sense but I'm not sure it will be possible.

On a related note, I considered using the Rmd template and add the code for the first figure (https://github.com/coatesj/covidpreprints/blob/master/vignettes/preprint_plot.Rmd). What do you think?

2020-10-07 12:52 UTC, Bisaloo commented
Feedback from Mate:

> Thanks a lot, I think you guys did a great job explaining the background of the project, what was done at the Sprint with the site, and I also liked your future perspectives and conclusion, so I'd be happy to post it on the preLights website as it is.
>
> I just have some minor suggestions (but feel free to disagree them!):
>
> - [ ] Probably the title is perfect for the rOpenSci page, but I wondered whether it might be too technical for the audience of preLights. If you are fine with having different titles for the two sites, I'd suggest doing away with the technical information of the packages used in the update, and rather mention the event in the title, e.g. 'Updating and automating the covidpreprints.com website during the eLife Sprint 2020' or 'We updated the covidpreprints.com website during the eLife Sprint 2020'
>
> - [ ] You could consider adding a little bit more info about how the event itself worked out, how you communicated within the team and with other teams, whether you presented the outcome of your work at the end in some kind of 'show and tell' etc. Perhaps obvious, but might be good to mention that the event took place in a virtual setting (at the moment I don't think that's so clear from the post)
>
> - [x] The end of this sentence needs to be fixed "We identified two goals at the start of the pre-print: " (I guess you meant 'sprint' instead of 'pre-print' 
>
> - [ ] Since you mention the Altmetric packages in the title, I was missing a bit the explanation of why you added it (the motivation for having it and why this is helpful for the user)
>
> - [ ] I don't know an easy way to fix this, but I thought in the 'Future perspectives' the transition from the first paragraph (where you talk about the future plans for technical updates) to the second paragraph (where you talk about the future of the project) could be made smoother, or potentially combined into one paragraph (in which case I'd start with the first sentence of your second paragraph "Experts from all around the world are asking..." and weave in the content of the second paragraph in a slightly shortened form). But probably this is a bit picky, so of course feel free to leave as is 
>
> - [ ] Minor thing, but I'd put the Acknowledgements beneath the 'Conclusion' (otherwise people might not read it - I actually missed this part during my first read of the post)
>
> - [ ] For the post that goes on the preLights site, you could consider including a 'call to action' or invitation for people to contribute by filling in the Google form. Perhaps this would best work at the end of the post. (I know you mention in the post that "Now, any netizen can nominate a preprint via this google form", but good to try to get people involved by more directly telling them that their contribution would be greatly appreciated).

2020-10-07 20:53 UTC, stefaniebutland commented on content/blog/2020-10-13-covidpreprints/index.md
> +Fortunately, we identified a significant part of the process that could be automated by fetching information from the Europe PMC API. More precisely, this could be done directly in R with a single fu
or link [Europe PMC](https://europepmc.org/About)

2020-10-07 21:01 UTC, stefaniebutland commented on content/blog/2020-10-13-covidpreprints/index.md
> +1. Get the altmetric score of each publication with the [rAltmetric](https://docs.ropensci.org/rAltmetric/) package
Footnote in addition to, since they give name credit to authors. I'll leave this to your decision. 

e.g. 
Najko Jahn (2020). europepmc: R Interface to the Europe PubMed Central RESTful Web Service. R package version 0.4.

Karthik Ram (2017). rAltmetric: Retrieves Altmerics Data for Any Published Paper from 'Altmetric.com'. R package version 0.7.0.

2020-10-07 22:57 UTC, stefaniebutland commented on content/blog/2020-10-13-covidpreprints/index.md
> +Here is a quick rundown of our update process:
> long/complicated

ah, I see your point about complicated code.

> What do you think?

sounds good - up to you

2020-10-08 16:05 UTC, stefaniebutland commented
@Bisaloo I won't chime in any further until you tell me you're finished. The updates look great.

2020-10-08 21:51 UTC, Bisaloo commented
> @Bisaloo I won't chime in any further until you tell me you're finished. The updates look great.

Yes, thank you! I just need to add some code chunks tomorrow and it should be ready for a second look. I'll let you know.

2020-10-09 17:04 UTC, Bisaloo commented
Hi @stefaniebutland, I'm off probably for the whole week end. The content is in its final version from our side and only the code chunks might change a bit (on Monday then I guess) but it's probably okay to have a look today if you have some time.

The first code chunk is set as `eval = FALSE` because it was taking too much time to run. Please let us know if it should be removed.

2020-10-09 18:17 UTC, stefaniebutland approved these changes
Here are my final comments. I'll publish Tues Oct 13 and tweet ~ 8am Pacific time tagging the 3 authors and preLights. I will likely tweet-reply tagging some some folks in your footnotes. Thank you Hugo!!

I'll email Máté to see if he needs anything further. 

- I made one suggested commit & comment in `index.Rmd`.
- Thanks so much for adding the 2nd code chunk! I do think the 1st code chunk takes up too much space, interrupting the story at the top. You could remove it unless you think of a way to put it at the end as a pseudo-footnote.
- Optional: Twitter [card validator](https://cards-dev.twitter.com/validator) on the [post preview](https://deploy-preview-43--ropensci.netlify.app/blog/2020/10/13/covidpreprints/) looks like this. To see full image, you'd need to include a different size copy of the image specifically for Twitter Card :-(. Based on [Large Summary Card guidance](https://louisem.com/217438/twitter-image-size#:~:text=The%20image%20size%20for%20the,shown%20as%20a%20small%20square.) I think 1200 x 675; no more than 1MB; approximately 1.91:1 aspect ratio.

![Screen Shot 2020-10-09 at 10 52 46 AM](https://user-images.githubusercontent.com/11927811/95615756-98dece00-0a1d-11eb-90af-ad3e94b091b4.png)

2020-10-10 09:56 UTC, Bisaloo commented
Someone at the sprint designed this graphical summary. Do you think it'd make a better twitter card? Or just the logo but smaller?

![covidpreprints image_dasapta_png](https://user-images.githubusercontent.com/10783929/95652180-9e0c4d80-0aef-11eb-85bb-c2eb8c73fe28.png)

2020-10-10 18:07 UTC, stefaniebutland commented
> Do you think it'd make a better twitter card? Or just the logo but smaller?

Logo. (a tank image not ideal for an international community)

2020-10-10 18:12 UTC, stefaniebutland commented
Need to knit? Updates not showing in [Preview](https://deploy-preview-43--ropensci.netlify.app/blog/2020/10/13/covidpreprints/)

2020-10-13 05:11 UTC, merged