Caro-Mo-Intro - blog post skeleton
ropensci/roweb3 pull request #551
Opened 2023-04-27 16:03 UTC by yabellini

2023-05-02 16:46 UTC, yabellini commented
Hi, @caropradier and @drmowinckels here is the draft of your intro blog post.  I use the text and picture you already share with me.  You can review and made changes.  I think we can add some links to your projects and institutions if you want to.  

In case you can't review or suggest in this PR, please share the changes and/or link as comment here, and I will apply them on the blog post.

Thanks!!!

2023-05-02 18:32 UTC, drmowinckels requested changes
Just some minor details and links. Looks good. Thank you!

2023-05-02 18:32 UTC, drmowinckels commented on content/blog/2023-05-18-champions-program-teams/index.md
> +My name Athanasia (Mo) Mowinckel, and I hold a PhD in cognitive neuroscience, and am based in Oslo Norway. I was born in Athens, Greece of a Cypriot mother and a Norwegian father, and moved to Norway
```suggestion
My name Athanasia (Mo) Mowinckel, and I hold a PhD in cognitive neuroscience, and am based in Oslo, Norway. I was born in Athens, Greece, of a Cypriot mother and a Norwegian father, and moved to Norway with my family when I was 4. Here, I now work as a staff scientist and Research Software Engineer at the [Center for Lifespan Changes in Brain and Cognition](https://www.oslobrains.no/) at the [University of Oslo](https://www.uio.no/english/). 
```

2023-05-02 19:44 UTC, yabellini commented
@steffilazerte, this is also ready for your review.

2023-05-04 14:45 UTC, steffilazerte reviewed
Just some tweaks and author files needed :) 
* [X] post follows Content Guidelines
* [X] post follows Style Guide
* [X] title is in Title Case
* [X] publication date is ok -> CHECK
* [X] alternative text of images is informative
* [ ] author metadata is provided with correct folder name -> **Need both**
* [X] html not included in pull request of Rmd post
* [X] I ran `roblog::ro_lint_md()` on index.md
* [X] I ran `roblog::ro_check_urls()` on index.md
* [X] I ran a spell-check on index.md
* [X] YAML subject tags are ok ("tech notes" for tech notes; "community" for non-staff non-editor)
* [X] YAML field 'preface' is present if necessary

2023-05-04 14:45 UTC, steffilazerte commented on content/blog/2023-05-18-champions-program-teams/index.md
> +  - Athanasia Monika Mowinckel
Both need author files

2023-05-04 14:45 UTC, steffilazerte commented on content/blog/2023-05-18-champions-program-teams/index.md
> +_Carolina and Mo are already working on the eph package. we’re excited to see how it goes! Be sure to not miss the next series of introductions_
```suggestion
_Carolina and Mo are already working on the eph package. We’re excited to see how it goes! Be sure to not miss the next series of introductions_
```

2023-05-04 14:45 UTC, steffilazerte commented on content/blog/2023-05-18-champions-program-teams/index.md
> +A lot of my work centers around creating data pipelines and work flows for my colleagues. In this work, I often choose to create R packages, which is one of the main programming languages in my field
```suggestion
A lot of my work centers around creating data pipelines and work flows for my colleagues. In this work, I often choose to create R packages, which is one of the main programming languages in my field. I also create JavaScript applications and Hugo websites depending on the need of the project. I have been a reviewer for an rOpenSci package as well as for several [JOSS](https://joss.theoj.org/) submissions of R packages. I am currently part of the [R-Ladies Global leadership](https://www.rladies.org/about-us/global-team/), after 4 years in the R-Ladies Global team as part of website development, and 5 years as chapter organiser in Oslo.
```

2023-05-04 14:45 UTC, steffilazerte commented on content/blog/2023-05-18-champions-program-teams/index.md
> +I am a mentor in the rOpenSci Champions program and am looking forward to learning about mentor roles and be inspired by new R users expanding their community roles. I'm hoping the Champions program
```suggestion
I am a mentor in the rOpenSci Champions program and am looking forward to learning about mentor roles and to being inspired by new R users expanding their community roles. I'm hoping the Champions program will give me new insight into how another generation interacts with the community either as reviewers or as developers, and to learn with them about how we can open up and enable more users to take part in our activities. I also look forward to connecting and interacting with other mentors and learning about how to be a good counsellor to others.
```

2023-05-04 18:41 UTC, drmowinckels commented on content/blog/2023-05-18-champions-program-teams/index.md
> +  - Athanasia Monika Mowinckel
check #557 for my author file

2023-05-04 19:01 UTC, caropradier commented on content/blog/2023-05-18-champions-program-teams/index.md
> +  - Athanasia Monika Mowinckel
find mine in #558

2023-05-05 14:01 UTC, yabellini commented on content/blog/2023-05-18-champions-program-teams/index.md
> +  - Athanasia Monika Mowinckel
Thanks!

2023-05-05 15:27 UTC, merged