Add July 2023 coworking
ropensci/roweb3 pull request #562
Opened 2023-05-05 21:39 UTC by steffilazerte

2023-05-05 21:43 UTC, steffilazerte commented
Hi @maelle,
When you get a chance can you take a [look](https://deploy-preview-562--ropensci.netlify.app/events/coworking-2023-07/) at the preview event and let me know if you haven any suggestions for wording, etc.?
No hurry 😁, thanks!

2023-05-07 14:57 UTC, maelle requested changes
Thank you!! I added "brag document" everywhere as it might be more known.
I wonder whether it'd be weird to link to https://twitter.com/JennyBryan/status/1582862196870373377 -- that's where I learnt the phrase and know no other source.

2023-05-07 14:57 UTC, maelle commented on content/events/2023-07-04-coworking-2023-07.md
> +title: Social Coworking and Office Hours - Create/Update your 'Happy' File!
```suggestion
title: Social Coworking and Office Hours - Create/Update your 'Happy File'/'Brag Document'!
```

2023-05-07 14:57 UTC, maelle commented on content/events/2023-07-04-coworking-2023-07.md
> +This month we're focusing on the theme **Create/Update your 'Happy' File!**
```suggestion
This month we're focusing on the theme **Create/Update your 'Happy File' or ['Brag Document'](https://jvns.ca/blog/brag-documents/), listing your small and big accomplishments at work!** 
```

2023-05-07 14:57 UTC, maelle commented on content/events/2023-07-04-coworking-2023-07.md
> +- Explore what goes into a 'Happy File' and why you need one
```suggestion
- Explore what goes into a 'Happy File'/'Brag Document' and why you need one
```

2023-05-08 15:10 UTC, steffilazerte commented on content/events/2023-07-04-coworking-2023-07.md
> +This month we're focusing on the theme **Create/Update your 'Happy' File!**
I think that linking "Happy File" to Jenny's post here would be fine, it's a public source and gives some context/credit to where you got the term.

2023-05-08 15:25 UTC, merged