Talk mo-runiverse-posit
ropensci/roweb3 pull request #627
Opened 2023-08-30 19:00 UTC by yabellini

2023-08-30 19:33 UTC, yabellini commented on content/events/2023-09-19-mo-runiverse-posit.md
> +
```suggestion

At Posit Conf? Come to learn from Mo about R-Universe!

```

2023-08-30 19:36 UTC, yabellini commented
@drmowinckels would you like to review this event we create for your talk about r-universe?

2023-09-05 15:33 UTC, drmowinckels requested changes
Thank you for this!

2023-09-05 15:33 UTC, drmowinckels commented on content/events/2023-09-19-mo-runiverse-posit.md
> +Say goodbye to installation headaches and hello to a universe of possibilities with R-Universe! Take your R package development to new frontiers by organizing and sharing packages beyond the bounds o
```suggestion
Say goodbye to installation headaches and hello to a universe of possibilities with R-Universe! Take your R package development to new frontiers by organizing and sharing packages beyond the bounds of CRAN. R-Universe's reliable package-building process strengthens installation and usage instructions, resulting in fewer support requests and an easy installation experience for users. With webpages and an API for exploring packages, R-Universe creates a streamlined and tidy ecosystem for R-package constellations. Join me to learn how to explore the vastness of R-Universe and expand your package development possibilities!
```

2023-09-05 15:55 UTC, merged