R in Goverment Community Call
ropensci/roweb3 pull request #653
Opened 2023-09-29 19:49 UTC by yabellini

Placeholder

2023-10-02 21:45 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    bio: ""
```suggestion
    bio: "Luiza Andrade is the Data Analytics Lead at the University of Chicago's Development Innovation Lab. Her work focuses on incorporating non-traditional data sources into development research, promoting transparency and reproducibility in social sciences, and developing software tools to simplify research data work. Prior to joining DIL, she was a Junior Data Scientist at the World Bank’s Development Impact Evaluation department. Luiza is a Brazilian national and holds a BA and an MSc in economics from the University of Sao Paulo."
```

2023-10-02 21:46 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    bio: ""
```suggestion
    bio: "I am a statistician and R enthusiast. I believe in the use of data science for social good and have worked with several non-profit and research organizations."
```

2023-10-02 22:22 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    bio: "I am a statistician and R enthusiast. I believe in the use of data science for social good and have worked with several non-profit and research organizations."
```suggestion
    bio: "Ahmadou Dicko is a humanitarian data scientist, currently serving as a Statistics and Data Analysis officer at UNHCR regional bureau for West and Central Africa. He is a fervent advocate for reproducibility in the humanitarian sector and has built several R packages and tools to streamline data processes. With M.Sc. in Statistics and a Ph.D. in Climate Change Economics, Ahmadou combines his profound knowledge of economics and data science to drive transformative change in the humanitarian sector. He is the founder and co-organizer of the Dakar R User Group and a recognized leader in promoting data literacy and community building around humanitarian data science."
```

2023-10-02 22:23 UTC, yabellini commented on content/author/ahmadou-dicko/_index.md
> +github: dickoa
```suggestion
github: dickoa
img: img/community/ahmadou-dicko.jpg
```

2023-10-02 22:42 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    img: ahmadou-dicko.jpg
```suggestion
    img: img/community/ahmadou-dicko.jpg
```

2023-10-02 22:42 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    img: luisa-andrade.png
```suggestion
    img: img/community/luiza-andrade.jpg
```

2023-10-02 22:42 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    img: pablo-tiscornia.jpg
```suggestion
    img: img/community/pablo-tiscornia.jpeg
```

2023-10-02 22:51 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    img: img/community/luiza-andrade.jpg
```suggestion
    img: /img/community/luiza-andrade.jpg
```

2023-10-02 22:51 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    img: img/community/ahmadou-dicko.jpg
```suggestion
    img: /img/community/ahmadou-dicko.jpg
```

2023-10-02 22:51 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    img: img/community/pablo-tiscornia.jpeg
```suggestion
    img: /img/community/pablo-tiscornia.jpeg
```

2023-10-03 21:03 UTC, yabellini reviewed
Adding Karly's info. Using LinkedIn data.

2023-10-03 21:03 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    img: karly-harker.jpg
```suggestion
    img: /img/community/karly-harker.jpeg
```

2023-10-03 21:03 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    bio: ""
```suggestion
    bio: "Environmental Data Science Specialist at British Columbia Ministry of Environment and Climate Change"
```

2023-10-03 21:54 UTC, pablotis requested changes
Please find below the bio for Pablo Tiscornia:

_Pablo is a graduate in Sociology from the University of Buenos Aires, Argentina. Currently, he works at C40 Cities as a Data Scientist, with a focus on improving data workflows related to Climate Change. He also serves as an instructor for Data Processing with R for Social Sciences at several National Universities in Argentina. 
He has made significant contributions to the development of R as a co-author of various packages used by Argentina's leading official statistical offices (INDEC, MINTURyDEP, and DGEyC). He has also been a co-organizer of the R community in Buenos Aires._

2023-10-09 10:54 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    bio: ""
```suggestion
    bio: "Pablo is a graduate in Sociology from the University of Buenos Aires, Argentina. Currently, he works at C40 Cities as a Data Scientist, with a focus on improving data workflows related to Climate Change. He also serves as an instructor for Data Processing with R for Social Sciences at several National Universities in Argentina.
He has made significant contributions to the development of R as a co-author of various packages used by Argentina's leading official statistical offices (INDEC, MINTURyDEP, and DGEyC). He has also been a co-organizer of the R community in Buenos Aires."
```

2023-10-09 11:22 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +zoomurl:
```suggestion
zoomurl: https://numfocus-org.zoom.us/j/83100290068?pwd=c4bloSdA1zNaQ7IzJD83BHD3I54zab.1
```

2023-10-09 11:23 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    Meeting ID:
```suggestion
    Meeting ID:  831 0029 0068 
```

2023-10-09 11:23 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    Passcode:
```suggestion
    Passcode: 042189
```

2023-10-09 18:11 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +slug: oct2023-goverment
```suggestion
slug: oct2023-government
```

2023-10-10 11:37 UTC, maelle reviewed
Thank you!

2023-10-10 11:37 UTC, maelle commented on content/commcalls/2023-10-31/index.md
> +In this community call, our panelist will share their experiences and examples of projects with R at different levels of government and in different countries.  We invite you to learn about the chall
```suggestion
In this community call, our panelists will share their experiences and examples of projects with R at different levels of government and in different countries.  
We invite you to learn about the challenges and lessons learned from our panelists and attendees in their efforts to make their government data, processes, and analyses more open and reproducible.    
```

2023-10-10 11:37 UTC, maelle commented on content/commcalls/2023-10-31/index.md
> +    bio: "Environmental Data Science Specialist at British Columbia Ministry of Environment and Climate Change"
could this one be sentences too?

2023-10-10 11:37 UTC, maelle commented on content/author/luiza-andrade/_index.md
> +name: Luiza Andrade
no link at all?

2023-10-10 11:40 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    bio: "Environmental Data Science Specialist at British Columbia Ministry of Environment and Climate Change"
Unfortunately I only have that information.

2023-10-10 11:44 UTC, yabellini commented on content/author/karly-harker/_index.md
> +linkedin: https://www.linkedin.com/in/karlyharker/
```suggestion
linkedin: https://www.linkedin.com/in/karlyharker/
github: KarHarker
```

2023-10-10 11:45 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    bio: "Environmental Data Science Specialist at British Columbia Ministry of Environment and Climate Change"
```suggestion
    bio: "Karly Harker is an environmental Data Science Specialist at British Columbia Ministry of Environment and Climate Change"
```

2023-10-10 11:51 UTC, yabellini commented on content/author/luiza-andrade/_index.md
> +name: Luiza Andrade
```suggestion
name: Luiza Andrade
link: https://bfi.uchicago.edu/scholar/luiza-andrade/
```

2023-10-10 11:58 UTC, yabellini commented on content/commcalls/2023-10-31/index.md
> +    bio: "Karly Harker is an environmental Data Science Specialist at the British Columbia Ministry of Environment and Climate Change. Karly is an Environment and Resource Studies and Biology graduat
```suggestion
    bio: "Karly Harker is an environmental Data Science Specialist at the British Columbia Ministry of Environment and Climate Change. Karly is an Environment and Resource Studies and Biology graduate from the University of Waterloo."
```

2023-10-10 12:31 UTC, merged