October news
ropensci/roweb3 pull request #655
Opened 2023-10-10 08:34 UTC by maelle

2023-10-12 11:02 UTC, yabellini commented on content/blog/2023-10-20-news-october-2023/index.Rmd
> +TODO YANI
```suggestion
Since last year we started the translation and localization of our Spanish version of our [comprehensive guide to software development](https://devguide.ropensci.org/). We have a [first version in Spanish](https://devdevguide.netlify.app/es/preface.es.html) and now, thanks to the R Community initiative, we are working on the Portuguese version.

Our process includes the review of automatic translations by two people, and we need your help! 

If you are interested in collaborating with this community effort, please check the "TODO - Second Review" tab of [this project on GitHub](https://github.com/orgs/ropensci/projects/7) and let us know you want to collaborate by leaving a comment in the corresponding Pull Request.

All contributors will be added to the rOpenSci Slack, [listed on our multilingual publishing project webpage](/multilingual-publishing/) and acknowledged as authors of the Portuguese translation.
```

2023-10-12 11:06 UTC, yabellini commented on content/blog/2023-10-20-news-october-2023/index.Rmd
> +### Reminder: Our first community call in Spanish (and English too)
```suggestion
### Reminder: Three upcoming community call, and our first one in Spanish!
```

2023-10-12 11:07 UTC, yabellini commented on content/blog/2023-10-20-news-october-2023/index.Rmd
> +
```suggestion
### [R in Government](/commcalls/oct2023-government/)

In this community call, our panelists will share their experiences and examples of projects with R at different levels of government and in different countries.
We invite you to learn about the challenges and lessons learned from our panelists and attendees in their efforts to make their government data, processes, and analyses more open and reproducible. 

With [Luíza Andrade](https://ropensci.org/author/lu%C3%ADza-andrade/), [Karly Harker](https://ropensci.org/author/karly-harker/), [Ahmadou Dicko](https://ropensci.org/author/ahmadou-dicko/), [Pablo Tiscornia](https://ropensci.org/author/pablo-tiscornia/). 

**Tuesday, 31 October 2023 16:00 UTC** 
```

2023-10-12 11:08 UTC, yabellini commented on content/blog/2023-10-20-news-october-2023/index.Rmd
> +As global movements, Open Source and Open Science face language-based exclusion as most resources are in English. This affects scientists and research software engineers working in R, particularly th
```suggestion

## Multilingual Publishing

As global movements, Open Source and Open Science face language-based exclusion as most resources are in English. This affects scientists and research software engineers working in R, particularly those who don’t have English as their first language.
```

2023-10-16 02:46 UTC, noamross requested changes
Nice post! Just a couple of little things.  I edited in the .md first and then transferred the edits/comments to the .Rmd.

2023-10-16 02:46 UTC, noamross commented on content/blog/2023-10-20-news-october-2023/index.md
> +### Reminder: Three upcoming community call, and our first one in Spanish!
```suggestion
### Reminder: Three upcoming community calls, and our first one in Spanish!
```

2023-10-16 02:46 UTC, noamross commented on content/blog/2023-10-20-news-october-2023/index.md
> +The following packages recently became a part of our software suite:
Should this section be removed as it is empty?

2023-10-16 02:46 UTC, noamross commented on content/blog/2023-10-20-news-october-2023/index.md
> +### Call for comaintainers
```suggestion
### Call for co-maintainers
```

2023-10-16 02:46 UTC, noamross commented on content/blog/2023-10-20-news-october-2023/index.Rmd
> +### Call for comaintainers
```suggestion
### Call for co-maintainers
```

2023-10-16 02:46 UTC, noamross commented on content/blog/2023-10-20-news-october-2023/index.Rmd
> +### Reminder: Three upcoming community call, and our first one in Spanish!
```suggestion
### Reminder: Three upcoming community calls, and our first one in Spanish!
```

2023-10-16 02:46 UTC, noamross commented on content/blog/2023-10-20-news-october-2023/index.Rmd
> +### New packages
Can this section be removed if there are no packages in it?

2023-10-17 10:19 UTC, maelle commented on content/blog/2023-10-20-news-october-2023/index.Rmd
> +### New packages
yes! I'll do it last minute just in case

2023-10-17 10:24 UTC, maelle commented
thank you @noamross!!

2023-10-20 07:54 UTC, merged