Transparency report 2023.
ropensci/roweb3 pull request #703
Opened 2024-01-02 15:21 UTC by yabellini

2024-01-08 10:21 UTC, mpadge requested changes

2024-01-08 10:21 UTC, mpadge commented on content/blog/2024-01-05-transparency2023/index.md
> +* _Observations:_
Do we need the "Observations" here? Also note that i think we could and maybe should add a little more detail, in particular to clarify that our mediation was pursued until we were assured that the reporter was satisfied.

2024-01-08 10:39 UTC, yabellini commented on content/blog/2024-01-05-transparency2023/index.md
> +* _Observations:_
This was also a skeleton to help with the report. Please don't hesitate to change it.

2024-01-09 12:36 UTC, yabellini reviewed
Changes as suggested by Kara and mark.

2024-01-09 12:36 UTC, yabellini commented on content/blog/2024-01-05-transparency2023/index.md
> +* _Description of the incident:_
```suggestion
* _Description of the incident:_  We received a Code of Conduct report regarding sharing a paywalled article in Slack. After review, we found that this conversation did not violate the Code of Conduct guidelines. The conversation was voluntarily deleted from Slack by its participants.
```

2024-01-09 12:36 UTC, yabellini commented on content/blog/2024-01-05-transparency2023/index.md
> +* _Actions:_  We followed our protocols to investigate the incident and informed the reported and reporter of our decision and the outcome.
```suggestion

```

2024-01-09 12:36 UTC, yabellini commented on content/blog/2024-01-05-transparency2023/index.md
> +* _Observations:_
```suggestion

```

2024-01-10 09:26 UTC, mpadge approved these changes

2024-01-12 11:45 UTC, merged