Marketing your package blog
ropensci/roweb3 pull request #732
Opened 2024-02-16 11:54 UTC by yabellini

2024-02-16 13:05 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +- Maelle Salmon
```suggestion
- Maëlle Salmon
```
:nail_care: (I know I have a better keyboard :wink:)

2024-02-16 13:10 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +- Maelle Salmon
I feel an ache every time I write your name wrong because I can't set up my keyboard correctly.

2024-02-20 08:28 UTC, maelle reviewed
Added some comments, thanks so much for drafting this!

2024-02-20 08:28 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +Now that you have created your package, presenting it to the world is a crucial step to gain visibility and attract users.  In this blog post we suggest a series of activities and tools to let the pe
```suggestion
Now that you have created your package, presenting it to the world is a crucial step to gain visibility and attract users.  In this blog post we suggest a series of activities and tools to let the people that your package can help, know that it is available. 
```

easier to parse

2024-02-20 08:28 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +Create a comprehensive README that clearly explains what your package does, how to install it, how can user start using it. Include examples or use cases and any relevant information (or links to) th
```suggestion
Create a comprehensive README that clearly explains what your package does, how to install it, how users can start using it. Include examples or use cases and any relevant information (or links to) that can help users understand how your package can help them. 
```

2024-02-20 08:28 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +Create a universe on R-universe, which will help you by simplifying the installation of your package and provide with useful stats and information about it.  You can also publish it on CRAN or submit
```suggestion
Create a universe on R-universe, which will help users by simplifying the installation of your package and provide with useful stats and information about it.  You can also publish it on CRAN or submit it to our peer review process. All this steps will support you with discoverability and also to comply with quality standards.  
```

Add that the universe is a way to showcase one's collection of packages, like GitHub pinned repos?

2024-02-20 08:28 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +For example, things maintainers can do:
write a tech note for rOpenSci blog?

2024-02-20 08:28 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +For example, things maintainers can do:
even if it's in the following section.

2024-02-20 20:48 UTC, yabellini commented
It is ready for review now. I'm unsure about using > to highlight the rOpenSci support.  Happy to change the format.

2024-02-22 09:07 UTC, maelle requested changes
:pray:

2024-02-22 09:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +Create a comprehensive README that clearly explains what your package does, how to install it, how users can start using it. Include examples or use cases and any relevant information (or links to) t
```suggestion
Create a comprehensive [README](https://blog.r-hub.io/2019/12/03/readmes/) that clearly explains what your package does, how to install it, how users can start using it. Include examples or use cases and any relevant information (or links to) that can help users understand how your package can help them. 
```

2024-02-22 09:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +[Create a universe on R-universe](/blog/2021/06/22/setup-runiverse/), which will help users by simplifying the installation of your package and provide with useful stats and information about it. R-U
```suggestion
[Create a universe on R-universe](/blog/2021/06/22/setup-runiverse/), which will help users by simplifying the installation of your package, and which will provide with useful stats and information about it. R-Universe is also a way to showcase your packages collection. You can also submit it to our [peer review process](https://ropensci.org/software-review/) if in scope. You can [publish it on CRAN](https://cran.r-project.org). All these steps will support you with discoverability and also to comply with quality standards.  
```

2024-02-22 09:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +> If you package is part of the rOpenSci Suite you can [write a blog post or a tech note](https://blogguide.ropensci.org/) for our blog and we will share in our [monthly newsletter](/news/) and our s
why use a quote formatting?

2024-02-22 09:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +You can also share updates, tutorials, use cases, talks and events where you will participate to engage with users.
share those where?

2024-02-22 09:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +> For rOpenSci packages, we collect the use cases and feature them on the website as well as the package. We also have social media campaing, for example "A Package a Day" on Mastodon were we feature
```suggestion
> For rOpenSci packages, we collect the [use cases](/use-cases) and feature them on the website as well as the package. We also have social media campaigns, for example "A Package a Day" on Mastodon were we feature one package of our suite each day. On LinkedIn we publish every Monday our "Package Weekly Digest" with a list of five package that belong to the same category.
```

2024-02-22 09:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +If you like to give talks, you can speak at an R User Group or R-Ladies Chapter, organizers invite spekaers but most of the groups are open to people that offer to give a talk or teach a workshop. Pr
```suggestion
If you like to give talks, you can speak at an R User Group or R-Ladies Chapter, organizers invite speakers but most of the groups are open to people that offer to give a talk or teach a workshop. Present your package on a field specific conference is another way to reach your users and get greater exposure.  There are R specific conferences like useR!, LatinR, satRdays and Posit::Conf. 
```

add links to the conference?

2024-02-22 09:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +> You can also propose an [rOpenSci Community Call](/commcalls/) relate with your package. For example, this community call about [targets](/commcalls/jan2023-targets/) has a panel with two users sho
I really think it'd be best not to use quote ">". Maybe instead split this section into "general advice" and "advice specific to rOpenSci packages"?

2024-02-22 10:44 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +> If you package is part of the rOpenSci Suite you can [write a blog post or a tech note](https://blogguide.ropensci.org/) for our blog and we will share in our [monthly newsletter](/news/) and our s
I wasn't sure on how to highlight the rOpenSci support, I'm not convinced on using quote formatting.

2024-02-22 10:44 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +You can also share updates, tutorials, use cases, talks and events where you will participate to engage with users.
Oh, on social media! I will add that.

2024-02-22 10:54 UTC, yabellini reviewed
Removing quote formatting

2024-02-22 10:54 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +> If you package is part of the rOpenSci Suite you can [write a blog post or a tech note](https://blogguide.ropensci.org/) for our blog and we will share in our [monthly newsletter](/news/) and our s
```suggestion
If you package is part of the rOpenSci Suite you can [write a blog post or a tech note](https://blogguide.ropensci.org/) for our blog and we will share in our [monthly newsletter](/news/) and our social media.
```

2024-02-22 10:54 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +You can also share updates, tutorials, use cases, talks and events where you will participate to engage with users.
```suggestion
You can also use your social media and your blog (if you have one) to share updates, tutorials, use cases, talks, and events where you will participate to engage with users. 
```

2024-02-22 10:54 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +> rOpenSci have two hours [co-working sessions each month](/coworking/), you can host a co-working session on the topic of the package.
```suggestion
rOpenSci have two hours [co-working sessions each month](/coworking/), you can host a co-working session on the topic of the package.
```

2024-02-22 10:54 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +> You can also propose an [rOpenSci Community Call](/commcalls/) relate with your package. For example, this community call about [targets](/commcalls/jan2023-targets/) has a panel with two users sho
```suggestion
You can also propose an [rOpenSci Community Call](/commcalls/) relate with your package. For example, this community call about [targets](/commcalls/jan2023-targets/) has a panel with two users showing how they use the package and the principal author sharing new insights about the package.
```

2024-03-05 16:01 UTC, steffilazerte reviewed
Hi @yabellini,
Just a couple of suggestions, a very useful post I think!

* [X] post follows Content Guidelines
* [X] post follows Style Guide
* [ ] title is in Title Case
* [ ] publication date is ok
* [X] alternative text of images is informative
* [X] author metadata is provided with correct folder name
* [X] html not included in pull request of Rmd post
* [X] I ran `roblog::ro_lint_md()` on index.md
* [X] I ran `roblog::ro_check_urls()` on index.md
* [X] I ran a spell-check on index.md
* [ ] YAML subject tags are ok ("tech notes" for tech notes; "community" for non-staff non-editor)
* [X] YAML field 'preface' is present if necessary

2024-03-05 18:28 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +Now that you have created your package, presenting it to the world is a crucial step to gain visibility and attract users.  In this blog post we suggest a series of activities and tools to let the pe
The whys I consider important are in the text (I can try to made them more clear):  
- "presenting it to the world is a crucial step to **gain visibility and attract users.**"
-  "to let the people that **your package can help know that it is available**. " 

But, other reason are completely valid too.  Should we list more options in the intro?

2024-03-05 22:54 UTC, steffilazerte commented on content/blog/2024-02-23-package-marketing/index.md
> +Now that you have created your package, presenting it to the world is a crucial step to gain visibility and attract users.  In this blog post we suggest a series of activities and tools to let the pe
I guess my question was not so much why promote, but *why do you want to attract users* in the first place? I mean, users just mean more people bugging you with their problems, right? 🤣  Why do you even need users if they're not buying the product? What's the benefit? 

That was the gist of my thought process. So I would say, add one reason to qualify why you would want to get more users.

2024-03-05 23:08 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +Now that you have created your package, presenting it to the world is a crucial step to gain visibility and attract users.  In this blog post we suggest a series of activities and tools to let the pe
To reach the people you package can help 😀.

2024-03-05 23:10 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +Now that you have created your package, presenting it to the world is a crucial step to gain visibility and attract users.  In this blog post we suggest a series of activities and tools to let the pe
I added some more info for this point. Thank you! 🙏

2024-03-06 06:07 UTC, maelle reviewed
:tada: Thanks so much Yani and Steffi!

I added a few comments. I have one last thought: should we make the word "marketing" appear somewhere in the title or intro or conclusion? It's only in the PR title at the moment. :smile_cat: 

I think we could publish it Wednesday 5th or Thursday 6th?

2024-03-06 06:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +## Publish
Sorry not to have thought of this sooner, should we mention pinning repositories on one's GitHub account if using GitHub? https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/pinning-items-to-your-profile

2024-03-06 06:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +If you like to give talks, you can speak at an R User Group or [R-Ladies Chapter](https://www.meetup.com/pro/rladies/). Organizers invite speakers but most groups are open to offers to give a talk or
```suggestion
If you like to give talks, you can speak at an R User Group or [R-Ladies Chapter](https://www.meetup.com/pro/rladies/). Organizers invite speakers but most groups are open to offers to give a talk or teach a workshop. Presenting your package at a domain-specific conference is another way to reach users and gain greater exposure. There are also R-specific conferences like [useR!](https://events.linuxfoundation.org/user/), [LatinR](https://latin-r.com/), [satRdays](https://satrdays.org/) and [Posit::Conf](https://posit.co/conference/). 
```

2024-03-06 06:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +If your package has a broad scope, you can also propose an [rOpenSci Community Call](/commcalls/) on your package. For example, a community call about [targets](/commcalls/jan2023-targets/) included
```suggestion
If your package has a broad scope, you can also propose an [rOpenSci Community Call](/commcalls/) on your package. For example, a community call about [targets](/commcalls/jan2023-targets/) included a panel with two users showing how they use the package and the principal author sharing new insights about the package. Alternatively, consider getting together with other package authors and proposing a domain-related Community Call, covering the use of several, more specific packages (for instance, [Research Applications of rOpenSci Taxonomy and Biodiversity Tools](/commcalls/2019-03-27/)).
```

2024-03-06 06:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +Publishing a paper about your package is an important aspect for academics developers. General R journals for publishing R packages are [The R Journal](https://journal.r-project.org) and the [Journal
```suggestion
Publishing a paper about your package is an important aspect for academics developers. General R journals for publishing R packages are [The R Journal](https://journal.r-project.org) and the [Journal of Statistical Software](https://www.jstatsoft.org/index), but remember that domain-specific journals may also publish R packages as tools for the field (for instance, [Methods in Ecology and Evolution](https://besjournals.onlinelibrary.wiley.com/journal/2041210x))
```

2024-03-06 06:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +The package that are peer reviwed by rOpenSci have a fast track for publication on the [Journal Open Source Software](https://joss.theoj.org).
```suggestion
The package that are peer-reviewed by rOpenSci have a fast track for publication on the [Journal Open Source Software](https://joss.theoj.org).
```

2024-03-06 06:07 UTC, maelle commented on content/blog/2024-02-23-package-marketing/index.md
> +
```suggestion
## Conclusion

```

2024-03-06 10:49 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +
```suggestion
If you use GitHub, you can [pin your package repository to your profile](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/pinning-items-to-your-profile) so other people can find it quickly. 
```

2024-03-06 10:49 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +Now that you have created your package, presenting it to the world is a crucial step to **gain visibility and attract users**. In addition to reaching the people your package can support, communicati
```suggestion
Now that you have created your package, presenting it to the world is a crucial step to **gain visibility and attract users**. 

Marketing your package effectively contributes to reaching the people your package can support, finding people to assist you in maintaining and improving your package and allowing you to learn about how people use it.
```

2024-03-06 10:49 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +Now that you have created your package, presenting it to the world is a crucial step to **gain visibility and attract users**. In addition to reaching the people your package can support, communicati
@maelle what about now?

2024-03-06 10:49 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +## Publish
Good idea!

2024-03-06 10:49 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +title: Spread the Word About Your Package
```suggestion
title: Marketing Ideas For Your Package
```

2024-03-06 10:49 UTC, yabellini commented on content/blog/2024-02-23-package-marketing/index.md
> +date: '2024-02-23'
```suggestion
date: '2024-03-06'
```

2024-03-06 13:26 UTC, yabellini commented
I have applied all the suggestions. I also expand on Help Wanted issues and tech notes looking for help.  I change the date to publish tomorrow. I will merge tomorrow mid-morning (for me) if we don't have more changes. :-)

2024-03-07 08:15 UTC, maelle commented
Awesome, thank you!

2024-03-07 12:20 UTC, merged