merge software review pages
ropensci/roweb3 pull request #873
Opened 2024-10-17 11:55 UTC by maelle

Fix #756

2024-10-19 02:59 UTC, noamross commented
I did a larger revision to make the higher-level benefits and goals of software review more forward, directing folks to the dev guides for more info.  Anything I missed?  Maybe we should add more links to some of the posts on peer review experience, chatops, development, etc?

2024-10-21 14:21 UTC, maelle commented
@noamross thank you!!

@mpadge can you also have a look before the "rest of us" gets a say?

2024-10-23 08:18 UTC, mpadge requested changes
Thanks @maelle for all this great work! I've suggested a couple of refinements, because I think the main, merged page could be improved by more clearly emphasising the distinction between the two streams of peer review. My suggestion here simply adds links to the scope definitions for each, which I think suffices, but am happy to iterate.

2024-10-23 08:18 UTC, mpadge commented on content/software-review/_index.md
> +Together, we use the peer review process create a [suite of high quality packages](/packages/) and a community of developers of users to support the long-term development and maintenance of scientifi
```suggestion
Together, we use the peer review process to curate a [suite of high quality packages](/packages/) and a community of developers of users to support the long-term development and maintenance of scientific software. rOpenSci's software peer-review relies on the volunteer work of _[editors](#editors)_, who manage the incoming flow and ensure progress of submissions; _authors_ who create, submit and improve their packages, and  *[reviewers](https://devguide.ropensci.org/softwarereview_intro.html#reviewers)*, who examine software source code and documentation.
```

2024-10-23 08:18 UTC, mpadge commented on content/software-review/_index.md
> +rOpenSci's peer review focuses on scientific applications, specifically tools related to scientific data lifecycle and statistical algorithms. You can read more about our standards, process, and how
```suggestion
rOpenSci's peer review focuses on scientific applications, and we accept submissions of packages related to [scientific data lifecycles](https://devguide.ropensci.org/softwarereview_policies.html#aims-and-scope) and [statistical algorithms](https://stats-devguide.ropensci.org/overview.html#overview-categories). You can read more about our standards, process, and how to participate in peer review in our [development guide](https://devguide.ropensci.org/index.html) and our [guide for statistical software](https://stats-devguide.ropensci.org/index.html).
```

2024-10-23 09:06 UTC, maelle commented
@yabellini @steffilazerte could you please have a look?

2024-10-23 09:06 UTC, maelle commented
@mpadge thank you! @noamross did the most of the work, my role was opening the PR :wink:

2024-10-23 09:15 UTC, mpadge approved these changes

2024-10-23 14:52 UTC, steffilazerte reviewed
Hi all, 
I reviewed the landing page (mostly) and offer some technical tweaks to the main paragraph and a number of opinionated suggestions for the resource cards. 

To my eye the resource cards aren't consistent and are sometimes unclear. As this is where people will go to learn more or act on things, I think it's important that they can do that easily. 

 I've suggested a different order, and different text. I also suggest replacing the link in the statistical sofware review context.

Let me know how you feel!

2024-10-23 14:52 UTC, steffilazerte commented on data/resources/softwarereview.json
> +   "url": "https://github.com/ropensci/software-review-meta/issues"
Should these titles or text reflect that these cards refer to the different types of review? And perhaps simplified a bit?
```suggestion
   "title": "Discussions of software review",
   "text": "A repository for 'meta' discussions of the standards and processes of software peer review",
   "url": "https://github.com/ropensci/software-review-meta/issues"
```

2024-10-23 14:52 UTC, steffilazerte commented on data/resources/softwarereview.json
> +},
These posts are not necessarily the context of statistical software review. It's possible that we'll have a community blog post about someone's statistical software package with this tag in future (actually now that I think of it I think there are posts already that should have this tag). 

I wonder if this card should actual be "Blog posts for statistical software review" and put at the end of the card list with the other "Blog posts" card. Then, pick one blog post that describes the "Context for statistical software review" and put *that* card after the "Context for software review" (to maintain the correct order, standard then statistical, throughout). Possibly with a description parallel to the other: "Blog post introducing statistical software review".

However if we create another card we will end up with an extra line of cards. So perhaps this card can become a link to a specific blog post and we could add the tag "Software peer review" to [this blog post](https://deploy-preview-873--ropensci.netlify.app/blog/2019/12/03/mark-padgham/), which is the only statistical software tagged post without *also* a "Software peer review" tag. That way the "Blog posts" card will link to all posts about either standard or statistical software review and we could omit the card for specifically statistical software blog posts.

2024-10-23 14:52 UTC, steffilazerte commented on data/resources/softwarereview.json
>     "text": "Blog post introducing the system",
```suggestion
   "text": "Blog post introducing software review",
```

2024-10-23 14:52 UTC, steffilazerte commented on content/software-review/_index.md
> +rOpenSci's Software Peer Review program brings together scientists and software engineers to improve the quality, reliability, and maintainability of scientific R packages through a **transparent, co
I'm a fan of Oxford commas, especially in the second example with such a long and complex list.
```suggestion
rOpenSci's Software Peer Review program brings together scientists and software engineers to improve the quality, 
reliability, and maintainability of scientific R packages through a **transparent, constructive, non adversarial, and open review process**. We bring together the best aspects of scientific peer review and open-source code review: recruiting expert developers and users to provide feedback, careful moderation and mentorship to provide a productive and inclusive environment, code diagnostics based on rOpenSci's deep experience in the R language, chatbot-supported interactions, and automation on open platforms for a smooth experience.
```

2024-10-23 14:52 UTC, steffilazerte commented on content/software-review/_index.md
> +and a community of developers of users to support the long-term development and maintenance of scientific software.
A "community of developers of users"? Should this be "and" users?
```suggestion
and a community of developers and users to support the long-term development and maintenance of scientific software. 
```

2024-10-23 14:52 UTC, steffilazerte commented on content/software-review/_index.md
> +submit and improve their packages,
For consistency
```suggestion
submit and improve their packages; 
```

2024-10-23 14:52 UTC, steffilazerte commented on data/resources/softwarereview.json
>     "title": "Volunteer",
Perhaps this card could go after "Submit a package" so that the two action items are at the beginning?

2024-10-23 14:52 UTC, steffilazerte commented on data/resources/softwarereview.json
>     "title": "Submit A Package",
For consistency
```suggestion
   "title": "Submit a package",
```

2024-10-28 06:27 UTC, noamross commented on data/resources/softwarereview.json
>     "title": "Volunteer",
I think we should cut back on the cards a lot for simplicity.  My preference for what to keep and order: "Dev Guide" -->, "Read More; Our development guide describes our standards and process for software peer review." "Volunteer to Review; Sign up to be a peer-reviewer of R packages", "More on our blog; Read posts from software peer-review authors, reviewers, and editors."

2024-10-28 10:51 UTC, mpadge commented on content/software-review/_index.md
> +and we accept submissions of packages related to [scientific data lifecycles](https://devguide.ropensci.org/softwarereview_policies.html#aims-and-scope)
```suggestion
and we accept submissions of packages related to our two software-review streams of [scientific data lifecycles](https://devguide.ropensci.org/softwarereview_policies.html#aims-and-scope) 
```
Just a suggestion, because I think the card duplication may still be a bit confusing. Some card title suggestions to also follow.

2024-10-28 10:52 UTC, mpadge commented on data/resources/softwarereview.json
> +   "title": "Discussion of our standards and process",
```suggestion
   "title": "Discussion of our statistical standards and process",
```

2024-10-28 15:12 UTC, steffilazerte commented on data/resources/softwarereview.json
>     "title": "Volunteer",
That would be four cards, which I think are in rows of three. So a bit unbalanced in the layout and also doesn't include a link to the Stats dev guide. Is that important?. Perhaps consider two alternatives: 
- Drop the Dev guide card, add an explicit link to both Dev Guide and Stats guide to the README that a view goes to when clicking on "Submit a Package". @maelle Could we also add all the guides (blog guide, contributing guide, dev guide, stats guide, r-universe guide) to the resources? I think that's where I would most naturally look for them if I knew they existed, but didn't know where?
- OR, add 1 more card (stats dev guide) to balance the layout a bit better

2024-10-28 15:26 UTC, noamross commented
Let's add the Stats Dev guide.

On Mon, Oct 28, 2024 at 11:12 PM Steffi LaZerte ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In data/resources/softwarereview.json
> <https://github.com/ropensci/roweb3/pull/873#discussion_r1819251296>:
>
> >     "text": "rOpenSci Packages: Development, Maintenance, and Peer Review including the aims and scope of our system.",
>     "url": "https://devguide.ropensci.org/"
>  },
>  {
> -   "title": "Discussion of our standards and process",
> -   "text": "A repository for 'meta' discussions",
> -   "url": "https://github.com/ropensci/software-review-meta/issues"
> +   "title": "Stats dev guide",
> +   "text": "rOpenSci Statistical Software Peer Review",
> +   "url": "https://stats-devguide.ropensci.org"
>  },
>  {
>     "title": "Volunteer",
>
> That would be four cards, which I think are in rows of three. So a bit
> unbalanced in the layout and also doesn't include a link to the Stats dev
> guide. Is that important?. Perhaps consider two alternatives:
>
>    - Drop the Dev guide card, add an explicit link to both Dev Guide and
>    Stats guide to the README that a view goes to when clicking on "Submit a
>    Package". @maelle <https://github.com/maelle> Could we also add all
>    the guides (blog guide, contributing guide, dev guide, stats guide,
>    r-universe guide) to the resources? I think that's where I would most
>    naturally look for them if I knew they existed, but didn't know where?
>    - OR, add 1 more card (stats dev guide) to balance the layout a bit
>    better
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ropensci/roweb3/pull/873#discussion_r1819251296>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAELS2BXWNCC4SG24K4A6ETZ5ZH7NAVCNFSM6AAAAABQDSHCI6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOJZGM4TQMZUGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-04 10:12 UTC, merged

2024-11-04 10:13 UTC, maelle commented
Thanks all, great team work :smile_cat: